let roleadores = [
  {
    nombre: "Mara",
    personajes: [
      "Adrián Firestone",
      "Sarah Firestone",
      "Isidoro Navarro",
      "Mei Feng",
      "Yados Mora",
      "Cata",
      "Liam Collins",
      "Kate Thompson",
      "Facundo Almenara",
    ],
  },
  {
    nombre: "Sweet",
    personajes: [
      "Thais Sweetwheath",
      "Shariel S.",
      "Ethan Sweetwheath",
      "Sascha Sweetwheath",
      "Segismundo",
      "Eleonore S.",
      "Pequeño Jonh",
      "Carsoon J.",
    ],
  },
  {
    nombre: "Mich",
    personajes: [
      "Samantha Anderson",
      "Michelle Byron de Sweetheath",
      "Harper Byron",
      "Dianna Evans",
      "Larissa Byron Sweetwheath",
      "Emma Klein",
      "Lia White-gluz",
      "Meghan Adler",
      "Charles Fraser",
    ],
  },
  {
    nombre: "Lolo",
    personajes: [
      "Lorna Castro",
      "Agente X",
      "Bo Xin",
      "Fito Olivares",
      "Aiden Holiday Castro",
      "Hazel Smith",
      "Morgan James",
      "Cole Hussain",
      "Leah Smith",
    ],
  },
  {
    nombre: "Blanca",
    personajes: [
      "Blanca Fermette Gambino",
      "Freddy Trucazo",
      "Toni Gambino",
      "Rogelio García",
      "Igor Junior Gambino",
      "Nick Hunter",
      "Eduard Reddington",
      "José Heredia",
      "James Gordon",
      "Filadelfo Casanova",
      "Ysabeau McCorrigan",
      "Ramona Domínguez",
      "Phoeniex Decker",
      "Leia Walsh",
      "Victoria Queen",
    ],
  },
  {
    nombre: "Internet Explorer",
    personajes: [
      "Vanu Lop",
      "Lucas Lop",
      "Toki Lop",
      "Yanelia Holmsther",
      "Canway",
      "Snowy",
      "Betty Garridone",
      "Sabrina Rodriguez",
      "Lorelei Welshon",
      "Cloe Ramirez",
      "Igor Cheryshev",
      "Mauro Lop",
      "Sebastian Lop",
      "Zendall Thenon",
    ],
  },
  {
    nombre: "Wen",
    personajes: [
      "Gwendolyn de Trucazo",
      "Jennifer King",
      "Elijah Müller",
      "Myke King",
    ],
  },
  {
    nombre: "Brillos",
    personajes: [
      "Brillith Torres",
      "Cesar Carter",
      "Ronald Gutierrez",
      "Alexandra Rivera",
    ],
  },
  {
    nombre: "Carlie",
    personajes: [
      "Jasha Volkov",
      "Carlo Gambino",
      "Carlie Lim",
      "Maxim Zaitsev",
      "Andrei Lim",
    ],
  },
  {
    nombre: "Madness",
    personajes: [
      "Bianca Madison Johnson",
      "Charlotte White-gluz",
      "Laoviah",
      "Milagros Johnson",
      "Alexander Johnson",
      "Christopher Johnson",
      "Lautaro Silva",
      "Caleb Wilson",
      "Matthew Moore",
      "Ezequiel Brown",
    ],
  },
  {
    nombre: "Nika",
    personajes: [
      "Nikaru Morningstar",
      "Alissa White-gluz",
      "Gustabo Garcia",
      "Lilith Morningstar",
      "Maiden Wright",
    ],
  },
  {
    nombre: "Pame",
    personajes: [
      "Pame Liu",
      "Ashley Carter",
      "Jia Lu",
      "Ivy Russ",
      "Hanna Sutcliff",
      "Kelly Thompson",
      "Emily Grey",
    ],
  },
  {
    nombre: "Danii",
    personajes: [
      "Daniela Gambino Lop",
      "Irina Molotov Karimov",
      "Alex Gray Martínez",
      "Jackson Bass",
      "Lexie Green",
    ],
  },
];

let personajes = [
  {
    nombre: "Adrián Firestone",
    rol: "Roleadora: Mara",
    biografia:
      "Llego a Asylum cuando se entero que su hermana, Sarah, fue ingresada al hospital por una sobredosis. Trabaja para los Sweet Dreams, le encanta disfrutar del momento y es un putero nato.",
    ocupacion: "Miembro de los Sweet Dreams",
    familia: "Sarah (hermana)",
    amigos: "Isidoro, Bo, Luis",
    historia: [
      "El y su hermana gemela nacieron en Argentina pero a una edad muy joven su padre los llevó a Los Santos para tener una mejor vida, pero pronto ambos fueron abandonados a su suerte por este. Los gemelos lograron sobrevivir trabajando desde jóvenes para maleantes, hasta que ambos se separaron por una pelea.",
      "Adrián se fue a vivir a Marbella, donde conoció a Bo en una carrera inlegal, donde este le ayudo a escapar de la policia. Desde entonces trabaja para él y se hizo gran amigo de este y varios integrantes de la banda.",
    ],
    curiosidades: [
      "Su emoji es 💖",
      "Es muy protector con su hermana.",
      "Conoce a Isidoro desde jóvenes, antes de que este ingresara a la CIA. Mantuvieron la amistad a pesar de que tomaron caminos opuestos.",
      "Le gusta coquetear con mujeres, sobre todo casadas, ya que le gusta el desafío.",
      "Es muy leal, aunque suele ser despreocupado con sus relaciones amorosas.",
      "No le gustan los mariscos ni la policía.",
      "Después de que un hombre enmascarado de toro lo atacara y lo dejara gravemente lastimado, generó una fobia hacia los toros.",
    ],
    recomendados: ["Cata", "Isidoro Navarro"],
  },
  {
    nombre: "Sarah Firestone",
    rol: "Roleadora: Mara",
    biografia:
      "Después de que su esposa le pidiera el divorció, tiene una sobredosis y queda en coma por un tiempo. Al final despierta, pero tiene perdida de memoria, olvidándose de su mujer y todo lo vivido en el pueblo.",
    ocupacion: "Desconocido",
    familia: "Adrián (hermano)",
    amigos: "Isidoro, desconocido",
    historia: [
      "El y su hermana gemela nacieron en Argentina pero a una edad muy joven su padre los llevó a Los Santos para tener una mejor vida, pero pronto ambos fueron abandonados a su suerte por este. Los gemelos lograron sobrevivir trabajando desde jóvenes para maleantes, hasta que ambos se separaron por una pelea.",
      "Sarah fue militar pero fue echada del cuerpo luego de agredir a un superior, quemandole el rostro. Se caso al poco tiempo de llegar a Asylum, pero luego de ser atrapada coqueteando con otras mujeres, su esposa le pide el divorcio y aborta el hijo que estaban esperando.",
    ],
    curiosidades: [
      "Su emoji es 🔥",
      "Le gusta los animales y el fuego (es pirómana).",
      "Conoce a Isidoro desde que eran jóvenes gracias a su hermano, lo considera como su segundo hermano.",
      "No entiende porque le gustaba ir a misa estando en Asylum, ya que nunca fue una persona religiosa.",
      "No le gustan los hombres ni aprueba que su hermano siga involuncrado con las ventas de drogas.",
      "Es una persona solitaria y guarda muchos secretos.",
    ],
    recomendados: ["Adrián Firestone", "Mei Feng"],
  },
  {
    nombre: "Isidoro Navarro",
    rol: "Roleadora: Mara",
    biografia:
      "Luego de un suceso que no recuerda, fue despedido del cuerpo y encomendada la misión, por parte de la CIA, de infiltrarse en los Sweet Dreams.",
    ocupacion: "Agente de la CIA",
    familia: "Desconocido",
    amigos: "Gustabo, Adrián, Sarah",
    historia: ["En desarrollo"],
    curiosidades: [
      "Su emoji es 🫀",
      "Su nombre original es Gonzalo, cambiado por la CIA. Los unicos que conocen su pasado son Adrián y Sarah.",
      "Le encanta salir con muchas mujeres, agenda a cada una como Chica enumerandolas. Pero su Chica numero 1 siempre sera Gustabo.",
      "Conocio a Adrián y a su hermana en las calles, cuando era joven y sobrevivia haciendo trabajos varios.",
      "Su sueño siempre fue trabajar como policia y finalmente, después de años no solo fue contratado en el cuerpo, sino como agente de la CIA.",
      "Desde la desaparición de Gustabo, Isidoro no ha parado de buscarlo.",
    ],
    recomendados: ["Adrián Firestone", "Sarah Firestone"],
  },
  {
    nombre: "Thais Sweetwheath",
    rol: "Roleadora: Sweet",
    biografia:
      "Llegó a Asylum cuando su abuelo la nombró sucesora de la familia/mafia y llegó al pueblo a hacer negocios.",
    ocupacion: "Mafia Sergeyev",
    familia: "Michelle, Harper y Ethan",
    amigos: "Shariel",
    historia: [
      "Fue criada por su abuelo y hermana gemela después de presenciar el suicidio de su madre, tuvo múltiples entrenamiento y misiones donde vio morir a tanta gente que ahora no le toma tanta importancia a las vidas de sus agentes.",
      "Cuando la nombraron Sasha de la mafia creo una facción externa para atacar a su abuelo, en esa facción de reencontró con Shariel la que fue su prometida cuando eran niñas.",
    ],
    curiosidades: [
      "Tiene un amor obsesivo por su esposa y solo ella le importa.",
      "Le gusta su esposa y el cacahuete.",
      "No le gusta que toquen a su esposa y el chocolate.",
      "Su fuente de alimentos se basa en whisky y cacahuates.",
      "Su pasatiempo preferido es estar con su esposa.",
      "Cuando se molesta comienza a hablar en ruso.",
      "Le gusta ver cómo Ethan se divierte asesinando gente",
    ],
    recomendados: ["Michelle Byron de Sweetheath", "Ethan Sweetwheath"],
  },
  {
    nombre: "Ethan Sweetwheath",
    rol: "Roleadora: Sweet",
    biografia:
      "Su abuelo lo quería matar pero lo robo Shariel y lo llevo a Asylum con su tía Thais para que lo cuide. Es el segundo heredero de la mafia.",
    ocupacion: "Mafia Sergeyev",
    familia: "Thais, Michelle y Harper",
    amigos: "No tiene",
    historia: [
      "Hijo de la hermana gemela de Thais, pensaron que era niña y su abuelo lo acogió, cuando descubrieron que era niño lo abandono en un sótano sin comida para que muriera.",
      "Shariel lo rescata y se lo entrega a la familia Byron Sweetwheath para que cuiden de el ahí conoció a su mamá y su hermano mayor.",
    ],
    curiosidades: [
      "Le gusta sus mamás, su hermano y los cacahuetes.",
      "No le gusta que lo lastimen y el chocolate.",
      "Imita al 100% a Thais cuando trabajan y le gusta salir con ella.",
      "Su pasatiempo preferido es matar gente pero prefiere quedarse con su familia.",
      "Cuando habla o le dice algún secreto a  Thais lo hace en ruso.",
      "Le gusta amenazar a sus empleados.",
    ],
    recomendados: ["Thais Sweetwheath", "Shariel S."],
  },
  {
    nombre: "Shariel S.",
    rol: "Roleadora: Sweet",
    biografia:
      "Mano derecha de Thais, se hace cargo de mover merca en el pueblo y ahora se hace cargo completamente del negocio en el pueblo.",
    ocupacion: "Mano derecha de la Sasha",
    familia: "Mikhail (muerto)",
    amigos: "Thais",
    historia: ["En desarrollo."],
    curiosidades: [
      "Le gusta el coito ,el chocolate y puchula.",
      "No le gusta la religión y las dagas.",
      "Es muy tímida cuando alguien le gusta.",
      "Le encanta asesinar a la gente en el coito.",
      "No le gusta hablar en ruso.",
      "Solo come pasteles y Malteadas.",
    ],
    recomendados: ["Thais Sweetwheath", "Ethan Sweetwheath"],
  },
  {
    nombre: "Samantha Anderson",
    rol: "Roleadora: Mich",
    biografia:
      "Vuelve a Asylum después de la muerte de su pareja Jace en Nueva Orleans, consigue trabajo en el hospital y se queda viviendo una vida relativamente tranquila, le encanta su trabajo y también cocinar.",
    ocupacion: "Enfermera en el hospital de Asylum",
    familia: "Grace y Henry Anderson",
    amigos: "Sherlyn Knox (muerta)",
    historia: [
      "Nace en Asylum y vive ahí la mayor parte de su vida hasta que decide mudarse para ir a estudiar a la universidad de nueva Orleans, ahí conoce a Jace que después de unos meses le pide ser su novia, continúan siendo pareja hasta que un fatídico día ocurre un robo a el apartamento de su novio donde las cosas salen mal dejándola con una herida de bala y a Jace muerto.",
      "Al pasar de los años sufre de depresión severa y ansiedad, sus padres la convencen de regresar a el pueblo y de ahí comienza a mejorar y superar la muerte de Jace, desde que regresa comienza a volver a amar su profesión y a tratar de disfrutar la vida.",
    ],
    curiosidades: [
      "Le gusta los postres dulces, cocinar, hablar con los pacientes y ayudar a las personas.",
      "No le ver a gente que le importa herida ni recordar el pasado.",
      "Después de el accidente su mano derecha comenzó a temblar cada vez que esta nerviosa o preocupada.",
      "Es alérgica a las nueces.",
      "Carga un dije con ella desde hace varios años.",
      "Es hija única.",
      "Se le es difícil conocer gente nueva y abrirse a las personas.",
    ],
    recomendados: ["Thais Sweetwheath", "Ethan Sweetwheath"],
  },
  {
    nombre: "Michelle Byron de Sweetheath",
    rol: "Roleadora: Mich",
    biografia:
      "Llega a asylum para tomar un largo descanso después de su última misión exitosa, esta casada con Thais sweetheart y tiene dos hijos, solo está en casa o con su esposa, le gusta divertirse y salir a beber pero casi no lo hace.",
    ocupacion: "En descanso de misiones militares",
    familia: "Harper Byron (hermano)",
    amigos: "Pame y Bitter (ella las considera)",
    historia: [
      "Su hermano y ella nacen en Londres Inglaterra donde cuando ambos eran adolescentes sufren la pérdida de ambos padres, duraron en Londres juntos hasta la muerte de su adorado hermano Harper el cual fue dado muerto a la edad de  18 años dejando así a una Michelle de tan solo 16 años sola.",
      "El quedarse sola la lleva a enlistarse en un tipo escuadrón militar durando así 6 años en combate y misiones al terminar el último año decide tomar un descanso y termina en asylum donde conoce a su ex esposa y esposa actual, después del nacimiento de su hijo deciden irse a vivir a Londres donde ahora sigue viviendo felizmente con su familia.",
    ],
    curiosidades: [
      "Le gusta su esposa, cuidar de sus hijos, combates cuerpo a cuerpo y el chocolate.",
      "No le gusta consumir cosas muy saladas, no ver a sus hijos o esposa.",
      "Después de la muerte de su hermano olvidó gran parte de su vida.",
      "Tuvo dos parejas en su estancia como militar.",
      "Es fiel, sentimental, es algo indiferente cuando se trata de personas que no significan nada para ella.",
    ],
    recomendados: ["Harper Byron", "Thais Sweetwheath"],
  },
  {
    nombre: "Harper Byron",
    rol: "Roleadora: Mich",
    biografia:
      "Nace en Londres y vive la mayor parte de su vida ahí, perdió gran parte de su vida al estar en coma, al despertar descubre que fue dado por muerto y su hermana abandonó la ciudad donde crecieron ambos y decide esperar a que vuelva.",
    ocupacion: "Asesino a sueldo",
    familia: "Michelle Byron, Alexander y Alison Byron (muertos)",
    amigos: "Sin amigos",
    historia: [
      "Junto a su hermana nace y crece en Londres donde al nacer su hermana se vuelve como una figura paterna para ella y se encarga de cuidarla.",
      "Sufrió de varios abusos por parte de sus padres y recibió cada castigo que iba para su hermana ya que no quería que ella sufriera, después de la muerte de sus padres entra en conflicto en su mente lo cual lo lleva a querer terminar con su vida de ahí termina en coma durante algunos años, al descubrir que su hermana piensa que murió decide no enfrentarla ya que sabe que eso la dañaría de una forma que se prometió nunca hacerla sufrir, después de despertar se convierte en asesino a sueldo para llevar una vida decente.",
    ],
    curiosidades: [
      "Se dedica a observar a su hermana la mayor parte de su tiempo ya que la extraña demasiado.",
      "Le gusta el chocolate, los hombres  y cuidar a su hermana.",
      "No le gusta ver triste a su hermana y lo saldo.",
      "La frase que lleva consigo es ama con toda el alma.",
      "La frase que lleva consigo es ama con toda el alma.",
      "Es muy leal y amistoso.",
      "Le gusta cuidar a la gente que le importa",
    ],
    recomendados: ["Michelle Byron de Sweetheath", "Dianna Evans"],
  },
  {
    nombre: "Dianna Evans",
    rol: "Roleadora: Mich",
    biografia: "En desarrollo",
    ocupacion: "Paramedica",
    familia: "En desarrollo",
    amigos: "En desarrollo",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Michelle Byron de Sweetheath", "Harper Byron"],
  },
  {
    nombre: "Lorna Castro",
    rol: "Roleadora: Lolo",
    biografia:
      "Llegó desde Chicago a Los Santos junto a su esposo para dirigir el Hospital General de Los Santos, luego de cinco años es enviada a Asylum por el comité de medicina para dirigir ese hospital. Desde entonces ha habido una mejora tanto de hospital como de los servicios y atención que ofrece en el mismo.",
    ocupacion: "Directora del Hospital General de Asylum/ médico cirujano",
    familia:
      "Albert Castro (padre, inversor capitalista en diversas empresas), Elisabeth Hale (madre, pintora y escritora en sus tiempos libres), Noah Holiday (cónyuge, Jefe de policía)",
    amigos:
      "Wernobyl de Trucazo, Blanca Fermette Gambino, Freddy Trucazo y Hazel Smith",
    historia: [
      "Hija única de Albert Castro y Elisabeth Hale, se interesó en la medicina desde muy joven,  fue una prodigio y se graduó antes de tiempo por lo que aplicó a la universidad desde temprana edad, se especializó en el área de cirugía y ciencias genómicas. Conoció a su actual esposo cuando estaba terminando su residencia, se casaron a los dos años de conocerse.",
      "Sus padres murieron en un accidente aéreo tan solo dos años antes de conseguir el puesto de directora en Los Santos donde residió por cinco años hasta que la trasladaron a Asylum donde conserva el mismo cargo.",
    ],
    curiosidades: [
      "Le gusta pasar tiempo con su esposo en sus ratos libres.",
      "Le gustan los animales aunque no tiene ninguno por la falta de tiempo.",
      "Algún día le gustaría tener hijos propios.",
      "Es una persona bastante profesional.",
      "A pesar de su seriedad es alguien bastante amable y bondadosa.",
    ],
    recomendados: ["Leah Smith"],
  },
  {
    nombre: "Agente X",
    rol: "Roleadora: Lolo",
    biografia:
      "Esta en la CIA desde que tiene memoria, asesina entrenada, experimento del Proyecto NewGen posteriormente llamado Proyecto X-1278 y gente de nivel 7.",
    ocupacion: "Agente nivel 7, asesina profesional de la CIA",
    familia: "Desconocido",
    amigos: "Cole Hussain",
    historia: [
      "Raptada desde los primeros meses de vida, fue sujeto de experimento en el Proyecto NewGen, proyecto cuyos sujetos de prueba eran los bebés de agentes de nivel 7 para abajo, luego de eso fue entrenada por la división especial de agentes hasta convertirse en una asesina.",
      "Al manifestarse sus poderes, fue recluida en el laboratorio con tan solo diez años para volver a ser sujeto de experimentos; fue liberada de los mismos hasta los veinte y desde entonces fue subiendo de nivel al infiltrarse en misiones y asesinar objetivos de la CIA con ayuda de sus habilidades camaleónicas.",
    ],
    curiosidades: [
      "Debido a su alteración genética, se interesó en las ciencias genómicas y las estudio en su tiempo libre volviéndose una profesional en el tema.",
      "Desarrollo un leve rechazo hacia sus poderes por el trauma que le causaron los experimentos.",
      "De pequeña, cuando sus poderes mentales despertaron, tenía pesadillas.",
      "Cuando recién despertó su poder mental, las voces en su cabeza no tenían forma, solo eran ruidos fuertes y muy molestos.",
      "Sabe diez idiomas entre ellos el ruso, alemán, español, portugués, inglés y un largo etc.",
      "Su primera víctima fue a los siete.",
      "Cuando la telekinesis despertó era muy molesta pues terminaba atrayendo objetos involuntariamente.",
    ],
    recomendados: ["Lorna Castro"],
  },
  {
    nombre: "Bo Xin",
    rol: "Roleadora: Lolo",
    biografia:
      "Llegó a Asylum buscando ampliar su negocio y expandir el poder de los Sweet Dreams.",
    ocupacion:
      "Lider de la Mafia Sweet Dreams; conductor profesional de carreras ilegales",
    familia: "Desconocido",
    amigos: "Luis, Yados, Eduardo (Abuelo) y Adrián",
    historia: [
      "Empezó a delinquir a los trece años, edad en la cuál su padre Buah lo abandonó. Años después conoció a Luis, Yados y al abuelo formando así la banda de los Sweet Dreams; luego de mucho trabajo en el mundo ilegal se lograron posicionar como la mafia de armas y cocaína más poderosa de Los Santos.",
    ],
    curiosidades: [
      "Adora correr en carreras ilegales.",
      "Le encanta comprarse coches y luego tunearlos a su gusto.",
      "Su mejor amigo es Luisito.",
      "Su película favorita es Mulan.",
      "Le encanta la música K-pop.",
    ],
    recomendados: ["Adrián Firestone", "Lorna Castro"],
  },
  {
    nombre: "Blanca Fermette Gambino",
    rol: "Roleadora: Blanca",
    biografia:
      "Nació en Sicilia, Italia. Hija menor de los Gambino. Criada y entrenada para hacerse cargo de la CIA. Estudió psiquiatría y criminología. Llegó a Los Santos y al pueblo de Asylum en busca de algo en qué ocuparse y alejarse de su madre.",
    ocupacion:
      "Jefa de la CIA y del departamento de psiquiatría del hospital de Asylum",
    familia:
      "Tommaso Gambino (padre, ex-capo de la Cosa Nostra e inversionista. Actualmente fallecido.), Felice Castellano (madre, antigua jefa de la CIA), Toni Gambino (hermano mayor, capo de la Cosa Nostra y dueño de la cadena de supermercados Krule), Carlo Gambino (segundo hermano mayor, capo de la Cosa Nostra y dueño de la cadenas de supermercados Krule) y Daniela Gambino Lop (esposa, dueña del casino)",
    amigos:
      "Dani Gambino Lop, Wernobyl de Trucazo, Carlie Lim, Vanu Lop, Toni Gambino, Carlo Gambino, Brillith y Lorna Castro",
    historia: [
      "Desde pequeña fue criada como militar y entrenada de todas las maneras posibles para ser una jefa y saber todo tipo de defensa personal. Fue retenida en las instalaciones de la CIA durante toda su niñez y juventud donde fue torturada por agentes y su propia madre, y la mantuvieron lejos de sus hermanos. Estudió psiquiatría y criminología mientras estaba comprometida.",
      "Llegó a Los Santos para librarse de su madre y rompió su antiguo compromiso, el cual fue un trato a sus espaldas y se enteró el mismo día que su boda. Fue casi obligada a casarse y ese mismo día llegó a Los Santos. Su objetivo principal en la CIA es cambiar el sistema antiguo de su madre y hacer mejor las cosas.",
    ],
    curiosidades: [
      "Su emoji es 🍷",
      "Suele ser demasiada amable y generosa con las personas.",
      "Es difícil ganar su aprecio.",
      "Cree que todos son sus ratas de laboratorio exceptuando sus amigos y familia.",
      "Es ludópata. Cree que es genético.",
      "Diagnosticada con bipolaridad.",
      "Posee signos de ser sociopata.",
      "Es demasiado observadora y calculadora.",
      "Excesivamente manipuladora e inteligente.",
      "Casi nunca se calla.",
      "La familia es primero.",
      "Es sádica y despiadada cuando es necesario.",
      "No puede tener hijos.",
    ],
    recomendados: ["Toni Gambino", "Carlo Gambino"],
  },
  {
    nombre: "Freddy Trucazo",
    rol: "Roleadora: Blanca",
    biografia:
      "Nació en Galicia, España. Juventud relativamente normal. Se mudó a Los Santos desde joven. Formó parte de una banda y actualmente agente de la CIA.",
    ocupacion:
      "Agente Nivel 7 de la CIA y Superintendente de la LSPD,Los Santos Police Department y Juez.",
    familia:
      "Ricardo Trucazo (padre, carpintero. Actualmente fallecido.), Genoveva Trucazo (madre, sin ocupación registrada. Actualmente fallecida.), José María Trucazo (hermano mayor, jefe de la banda SL. Actualmente fallecido.) y Gwendolyn de Trucazo (esposa, abogada)",
    amigos: "Gwendolyn de Trucazo, Lorna Castro y Noah Holiday",
    historia: [
      "Se mudó a Los Santos siendo joven. En su juventud, formó parte del Cuerpo Nacional de Policia, CNP, pero fue despedido por comportamiento inadecuado. Inició una banda criminal junto a su hermano llamada SL. Después fue reclutado por Jack Conway en el CNI que posteriormente cambió su nombre a CIA. Su misión actual es mantener a la ciudad de Los Santos estable como Superintendente de la LSPD.",
    ],
    curiosidades: [
      "Su emoji como Freddy es 🪓 y como Toro es 🐃",
      "Padece de transtorno de identidad disociativo parcial.",
      "Actualmente se sabe que solo tiene un Alter que se hace llamar Toro.",
      "Es extremadamente, inteligente, manipulador y persuasivo.",
      "Se destaca en la agencia por ser sicario.",
      "No le gusta relacionarse con las personas o profundizar relaciones.",
      "Siempre quiso ser padre.",
      "Mató a su hermano.",
    ],
    recomendados: ["Gwendolyn de Trucazo", "Canway"],
  },
  {
    nombre: "Toni Gambino",
    rol: "Roleadora: Blanca",
    biografia:
      "Nació en Sicilia, Italia. Hermano mayor de la familia Gambino. Fue criado en casa y formado para ser el sucesor del imperio de su padre.",
    ocupacion:
      "Capo de la Cosa Nostra y Jefe/Dueño de la cadena de supermercados Krule",
    familia:
      "Tommaso Gambino (padre, ex-capo de la Cosa Nostra e inversionista. Actualmente fallecido.), Felice Castellano (madre, antigua jefa de la CIA), Carlo Gambino (hermano menor, capo de la Cosa Nostra y dueño de la cadenas de supermercados Krule) y Blanca Fermette Gambino (hermana menor, jefa de la CIA y psiquiatra)",
    amigos:
      "Carlo Gambino, Blanca Fermette Gambino, Gasolino López, José Heredia, Igor y Hai Cheng",
    historia: [
      "Desde pequeño fue criado como el jefe de la familia. Criado en casa y entrenado para formar parte y llevar la mafia de su padre. Fue destinado como el heredero de la Cosa Nostra. Se le enseñó a manejar armas y a ser buen negociador. Llegó a Marbella para establecer las bases del nuevo imperio después de la muerte de su padre y allí tuvo problemas con la policía y el FBI. Huyó junto a otros conocidos y amigos suyos en un avión y pidió asilo a su hermana. Después voló a Los Santos y actualmente se hospeda en Asylum. Sigue con su cadena de supermercados y establece la base para un nuevo imperio bajo la tutela de la CIA.",
    ],
    curiosidades: [
      "Su emoji es 🕶️",
      "Su padre siempre lo tachó de blando.",
      "Es muy inteligente y buen negociador.",
      "Ama a su mafia, pero prefiere el Krule.",
      "Es ludópata. Piensa que es genético.",
      "Siempre viste de traje.",
      "Fiel creyente religioso.",
      "Padece de heterocromía.",
      "Es demasiado amable para su puesto.",
      "Sobreprotector.",
      "Tenía pésima puntería hasta que su hermana le enseñó.",
    ],
    recomendados: ["Blanca Fermette Gambino", "Carlo Gambino"],
  },
  {
    nombre: "Vanu Lop",
    rol: "Roleadora: Internet Explorer",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Lucas Lop", "Toki Lop"],
  },
  {
    nombre: "Gwendolyn de Trucazo",
    rol: "Roleadora: Wen",
    biografia:
      "Llegó desde México a la edad de 12 años después de ser adoptada por Dem y Mad. Desde entonces no ha regresado a México, creció y formó su familia en Asylum.",
    ocupacion: "Abogada",
    familia:
      "Dem Johnson (padre, fallecido. Dios), Mad Johnson (madre, Sacerdotisa principal de la iglesia Asylum), Shey (hermana, sin ocupación), Nikaru Morningstar(madrastra, sin ocupación), Alexander Johnson (abuelo Paterno, Sacerdote líder de la Catedral Metropolitana. Argentina) y Freddy Trucazo (esposo, Superintendente LSP)",
    amigos:
      "Freddy Trucazo, Dani Gambino Lop, Blanca Gambino Lop, Lorna Castro, Puchula(Yanelia Holmsther)",
    historia: [
      "Nació y creció en México hasta la edad de doce años, edad en la cuál sus padres la adoptaron y trasladaron a Asylum, lugar que desde entonces ha sido su residencia. Se graduó de derecho en la universidad convirtiéndose luego en la mejor abogada de Asylum; conoció a su actual esposo en un juicio cuando ejercía su profesión.",
      "Sufrió un trauma cuando vio como su padre se degollaba en un intento de salvación hacia su madre. Fue secuestrada por la CIA al intentar huir junto a su esposo después de enterarse que estaba embarazada. Actualmente se encuentra gestando gemelos. No confía en nadie más que en su esposo y su mejor amiga.",
    ],
    curiosidades: [
      "Tiene una fijación por las cicatrices.",
      "Creció con el rechazo de su padre.",
      "Tomo de ejemplo la relación tóxica de sus padres para la propia.",
      "Tiene depresión, ansiedad, baja autoestima y apego ansioso.",
      "Tiene una relación obsesiva y posesiva con su esposo.",
      "Guarda partes del cuerpo de sus victimas como “Trofeos de Relación”.",
      "Es bastante protectora con sus seres queridos.",
      "Comparte una cicatriz ubicada en la mano izquierda con su esposo.",
      "Tiene en su pecho marcado el nombre de “Toro”.",
      "Tiene un perrhijo llamado “Canwey”",
      "Le encantan las coronas y las rosas.",
    ],
    recomendados: ["Freddy Trucazo", "Adrián Firestone"],
  },
  {
    nombre: "Brillith Torres",
    rol: "Roleadora: Brillos",
    biografia: "Llegó a Asylum por la misión que le encargó el FBI.",
    ocupacion: "Ex agente del FBI/ Dueña de la Cafetería de Asylum",
    familia: "Desconocido",
    amigos: "Pame Liu",
    historia: [
      "Fue entrenada en el FBI convirtiéndose en agente, llegó a Asylum cuando su jefa Vanu le encargó la misión de enamorar a Mad para sacar información de la misma. Luego de que todo saliera mal le borraron la memoria con ayuda de la CIA; tuvo que cambiar su aspecto físico y actualmente tiene una cafetería además de estar comprometida con la comisaría de Asylum.",
    ],
    curiosidades: [
      "Aprendió todo lo que sabe de cocina por su abuela.",
      "Se encariña rápido.",
      "Siempre quiso tener su propia familia.",
      "Le gusta mucho dar regalos a los que aprecia.",
      "Tener su propia cafetería es lo que siempre quiso.",
    ],
    recomendados: ["Blanca Fermette Gambino", "Adrián Firestone"],
  },
  {
    nombre: "Mei Feng",
    rol: "Roleadora: Mara",
    biografia:
      "Luego de que Sarah incendiara la casa donde estaba viviendo esperando a sus padres desaparecidos, decidió que era el destino y no piensa despegarse de ella.",
    ocupacion: "No tiene",
    familia: "Desconocido",
    amigos: "Sarah",
    historia: [
      "Vivía en una casa a las afueras de Asylum, hasta que ellos desaparecieron. Mei decidió esperarlos, quedándose varios años ahí sola, sobreviviendo de robar en las calles. Cuando Sarah apareció en su vida, decidió que era su destino enviada por su madre y no piensa despegarse de ella.",
    ],
    curiosidades: [
      "Su emoji es 🍭",
      "Le gustan los dulces.",
      "Le da miedo quedarse sola.",
      "Aunque por años a esperado la vuelta de sus padres, realmente teme que esten muertos",
      "En su corta vida, ha visto algunas cosas feas en las calles y ya poco le sorprende.",
      "Ha tenido que madurar para sobrevivir, pero sigue siendo una niña.",
    ],
    recomendados: ["Sarah Firestone", "Adrián Firestone"],
  },
  {
    nombre: "Jasha Volkov",
    rol: "Roleadora: Carlie",
    biografia:
      "Llegó a Asylum para verificar él mismo el progreso del trabajo de Carlie, su nieta, ya que de ella depende que su mafia siga en pie y sin represalias. Se mantiene al margen de la legalidad debido al puesto de su nieta.",
    ocupacion: "Jefe mayor de la Bratva",
    familia:
      "Carlie Lim (nieta), Yohan Lim (yerno, fallecido), Anastasia Lim Volkov (hija, fallecida), Barbie Lim (nieta menor, fallecida)",
    amigos: "Maxim Zaitsev",
    historia: [
      "Ruso, se hizo jefe de la Bratva a temprana edad, debido al fallecimiento prematuro de su padre, al no tener más hermanos, tuvo que aprender todo solo pero con ayuda de los miembros de la mafia, se convirtió en uno de los líderes mafiosos más grandes y respetados. Le dio refugio a un joven, cuya familia fue asesinada por una mafia enemiga, llamado Maxim, con el tiempo le enseñó todo lo necesario y lo convirtió en su mano derecha. Años atrás viajó a Asylum para establecer su mafia ahí y crear un imperio, sin embargo, ocasionó ciertos disturbios y descontrol en Asylum debido a que hizo una masacre de agentes del FBI. La agencia casualmente, o no, asignó a su yerno a llevar el caso de su mafia para desmantelarla, sin embargo, en un conflicto de intereses, su yerno borró todo registro de la mafia, y fue acusado por traición, provocando la ejecución de él y su familia, quedando como única sobreviviente, su nieta mayor, Carlie; la cual es la encargada ahora tanto del FBI como de la Bratva.",
    ],
    curiosidades: [
      "Sabe hablar español y ruso, pero prefiere usar el ruso.",
      "Muy tradicional.",
      "Carácter frío e insensible.",
      "Interesado.",
      "Elegante.",
      "Se preocupa por su imagen.",
      "Tiene una tolerancia alta al alcohol.",
      "Buen uso de armas y buena puntería.",
      "Excelente negociador.",
    ],
    recomendados: ["Maxim Zaitsev"],
  },
  {
    nombre: "Carlo Gambino",
    rol: "Roleadora: Carlie",
    biografia:
      "Llegó a Asylum para reencontrarse con su hermano Toni, sin saber que también conocería a su hermana menor. Quedó a cargo de la mafia de su padre junto a su hermano mayor.",
    ocupacion: "Capo de la Cosa Nostra y Jefe de la cadena Krule",
    familia:
      "Tommaso Gambino (padre, fallecido), Felice Castellano (madre), Toni Gambino (hermano mayor) y Blanca Fermette Gambino (hermana menor)",
    amigos:
      "Toni Gambino, Blanca Fermette Gambino, Gasolino López, José Heredia, Igor y Hai Cheng",
    historia: [
      "Nacido en Sicilia, Italia. Fue criado y educado en casa, para ayudar a su hermano mayor a llevar la mafia de su padre. Junto a Toni, llegó a Marbella para expandir su imperio, pero hubo problemas con la policía y el FBI, sin embargo, al querer junto a sus amigos y hermano, no logró tomar el avión, fue atrapado y condenado a reclusión en una isla, sin ningún tipo de contacto humano. Tiempo después fue liberado, regresó a Italia, donde le dijeron que su hermano, al que creía muerto, estaba en Asylum.",
    ],
    curiosidades: [
      "Ludópata.",
      "Mentiroso compulsivo.",
      "Usa su encanto para obtener lo que quiere cuando quiere.",
      "Sólo le interesa divertirse, ya sea con mujeres o apostando.",
      "No tiene escrúpulos.",
      "Le gusta ganar dinero sin esfuerzo alguno.",
      "Excéntrico.",
      "Tiene un estilo extravagante.",
    ],
    recomendados: ["Toni Gambino", "Blanca Fermette Gambino"],
  },
  {
    nombre: "Carlie Lim",
    rol: "Roleadora: Carlie",
    biografia:
      "Llegó a Asylum para unirse al FBI, como parte de un castigo a su padre, debido a problemas de intereses. Estudió finanzas y relaciones internacionales, heredó la empresa familiar de su madre una vez que se graduó. Casada con Pame Liu, a quien conoció en una misa.",
    ocupacion: "Directora del FBI y Directora General en Financiera Volkov",
    familia:
      "Yohan Lim (padre, fallecido), Anastasia Lim Volkov (madre, fallecida), Barbie Lim (hermana menor, fallecida), Jasha Volkov (abuelo), Pame Liu (esposa)",
    amigos:
      "Vanu Lop, Blanca Fermette Gambino, Dani Gambino Lop, Maxim Zaitsev",
    historia: [
      "Nacida en México, pero viviendo en Rusia hasta su traslado a Asylum, Hija de un agente élite del FBI, Yohan Lim, y una heredera de la Bratva, Anastasia Lim Volkov, y hermana mayor de Barbie Lim, quienes murieron en una emboscada por parte del FBI, debido a una traición por parte de Yohan, Carlie fue la única sobreviviente en esa emboscada. Buscó la venganza por la muerte de su familia, encontrando al agente que los asesinó y cortando sus dedos, para mandarlos al director del FBI, gracias a eso fue reclutada por el FBI, entrenó y se volvió de las mejores agentes del FBI; junto a Vanu, hizo un golpe de estado dentro de la agencia, volviéndose una de las directoras. Su identidad máscara es de una empresaria financiera, siendo de las más grandes en el ámbito. Antes de llegar a Asylum y conocer a Pame, tuvo una relación formal con Maxim Zaitsev, quien es mano derecha de su abuelo en la mafia.",
    ],
    curiosidades: [
      "Habla varios idiomas (español, inglés, ruso, coreano italiano y japonés).",
      "Leal con las personas que aprecia.",
      "Suele alejarse de la gente que la lastima.",
      "Odia los estupefacientes.",
      "Fuma a escondidas.",
      "Sufre insomnio por estrés postraumático.",
      "Tiene una fijación con las torturas y la mutilación.",
      "No le interesa la vida de los demás.",
      "Sólo se preocupa por su esposa y sus amigas.",
    ],
    recomendados: ["Pame Liu", "Vanu Lop"],
  },
  {
    nombre: "Maxim Zaitsev",
    rol: "Roleadora: Carlie",
    biografia:
      "Llegó a Asylum para reencontrarse con el amor de su vida, Carlie. También para ayudar a su jefe en sus negocios fuera de Rusia, una vez que todo ahí ya está bien establecido y controlado. Tiene intención de poner un estudio de tatuajes.",
    ocupacion: "Mano derecha del jefe mayor de la Bratva y tatuador",
    familia: "Jasha Volkov (jefe)",
    amigos: "Carlie Lim",
    historia: [
      "Su familia fue asesinada en un ataque de una mafia enemiga de la Bratva, Jasha al darse cuenta de que quedó desprotegido, lo acogió y lo crió como un hijo. Fue entrenado para hacer el trabajo de la mafia en ausencia del jefe. Con el tiempo, se enamoró de Carlie, con quien mantuvo una relación formal, hasta que ella fue trasladada a Asylum. Intentó olvidarla teniendo otras relaciones, pero no funcionó. Por lo que fue a buscarla allá. En su tiempo libre, estudió el arte del tatuaje, ahora que llegó a Asylum, planea poner su propio estudio.",
    ],
    curiosidades: [
      "Aprendió español para hablar con Carlie exclusivamente.",
      "Practicó sus tatuajes con sus compañeros de la mafia.",
      "Tiene un aura oscura, pero suele ser amable.",
      "Tiende a ser obsesivo con lo que le interesa.",
      "Distraído.",
      "Buena puntería y manejo de armas.",
      "Carismático.",
      "Baja tolerancia al alcohol.",
    ],
    recomendados: ["Jasha Volkov", "Carlie Lim"],
  },
  {
    nombre: "Bianca Madison Johnson",
    rol: "Roleadora: Madness",
    biografia: "En desarrollo",
    ocupacion: "Obispa de la iglesia en Asylum",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Gwendolyn de Trucazo", "Nikaru Morningstar"],
  },
  {
    nombre: "Nikaru Morningstar",
    rol: "Roleadora: Nika",
    biografia: "En desarrollo",
    ocupacion: "Trabaja para la cia y generar caos",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Bianca Madison Johnson", "Gwendolyn de Trucazo"],
  },
  {
    nombre: "Alissa White-gluz",
    rol: "Roleadora: Nika",
    biografia: "En desarrollo",
    ocupacion:
      "Comisaría y agente  y jefa del departamento de investigación  de la CIA",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Ezequiel Brown"],
  },
  {
    nombre: "Charlotte White-gluz",
    rol: "Roleadora: Madness",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Alissa White-gluz", "Freddy Trucazo"],
  },
  {
    nombre: "Jennifer King",
    rol: "Roleadora: Wen",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Elijah Müller", "Myke King"],
  },
  {
    nombre: "Laoviah",
    rol: "Roleadora: Madness",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Bianca Madison Johnson", "Milagros Johnson"],
  },
  {
    nombre: "Milagros Johnson",
    rol: "Roleadora: Madness",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Bianca Madison Johnson", "Laoviah"],
  },
  {
    nombre: "Elijah Müller",
    rol: "Roleadora: Wen",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Myke King", "Jennifer King"],
  },
  {
    nombre: "Myke King",
    rol: "Roleadora: Wen",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Elijah Müller", "Jennifer King"],
  },
  {
    nombre: "Larissa Byron Sweetwheath",
    rol: "Roleadora: Mich",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Emma Klein"],
  },
  {
    nombre: "Emma Klein",
    rol: "Roleadora: Mich",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Larissa Byron Sweetwheath"],
  },
  {
    nombre: "Alexander Johnson",
    rol: "Roleadora: Madness",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Christopher Johnson", "Bianca Madison Johnson"],
  },
  {
    nombre: "Christopher Johnson",
    rol: "Roleadora: Madness",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Alexander Johnson", "Bianca Madison Johnson"],
  },
  {
    nombre: "Lautaro Silva",
    rol: "Roleadora: Madness",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Freddy Trucazo"],
  },
  {
    nombre: "Lucas Lop",
    rol: "Roleadora: Internet Explorer",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Toki Lop", "Vanu Lop"],
  },
  {
    nombre: "Toki Lop",
    rol: "Roleadora: Internet Explorer",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Lucas Lop", "Vanu Lop"],
  },
  {
    nombre: "Yanelia Holmsther",
    rol: "Roleadora: Internet Explorer",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Vanu Lop"],
  },
  {
    nombre: "Canway",
    rol: "Roleadora: Internet Explorer",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Freddy Trucazo", "Gwendolyn de Trucazo"],
  },
  {
    nombre: "Snowy",
    rol: "Roleadora: Internet Explorer",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Canway"],
  },
  {
    nombre: "Cesar Carter",
    rol: "Roleadora: Brillos",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Canway"],
  },
  {
    nombre: "Pame Liu",
    rol: "Roleadora: Pame",
    biografia:
      "Después de una discusión muy grande con su padre, su madrastra le regala una casa en el pueblo Asylum, lejos de la ciudad para que pueda crecer y ser independiente.",
    ocupacion: "Mantenida",
    familia: "Carlie Lim (esposa), Andrei Lim (hijo) y Jia Liu (madrastra)",
    amigos: "Brillith Torres",
    historia: [
      "Toda su infancia fue maltratada física y psicológicamente, su madre murió a causa de unos medicamentos que le daban su padre y madrastra, su padre quiso venderla apenas su madre murió, pero su madrastra decidió quedársela y adoptarla, tiempo después Pame entro a un programa siendo un conejillo de indias de su madrastra para poder realizar sus investigaciones y ver si los medicamentos funcionaban de manera correcta, haciendo que en el proceso Pame olvidara muchas cosas y dejara de tener algunos sentimientos, llego a Asylum y después de enamorarse de Carlie dejo de tomar esos medicamentos que poco a poco la estaban matando.",
    ],
    curiosidades: [
      "Ama el color rosa.",
      "Tiene una personalidad inocente y tonta.",
      "Suele olvidar rápido las cosas.",
      "De vez en cuando tiene pesadillas que en realidad son recuerdos.",
      "Le gusta mucho estar en casa.",
      "Está dispuesta a morir por su esposa.",
    ],
    recomendados: ["Carlie Lim", "Brillith Torres"],
  },
  {
    nombre: "Ashley Carter",
    rol: "Roleadora: Pame",
    biografia:
      "Llego a Asylum por negocios y no piensa quedarse mucho tiempo, es jefa de los moteros desde los 18 años, la banda creció tanto que tiene informantes por todos lados, varios bares y hospitales ilegales, nunca se quedan mucho tiempo en una ciudad.",
    ocupacion:
      "Jefa de los motociclistas, dueña de un bar y el hospital clandestino",
    familia:
      ": Cesar Carter (hermano mayor), James Carter (hermano menor) y Carsoon J (novio)",
    amigos:
      "Brendon Asmodeo, Sofia Miller, Breyden Liebhaber, Henry Beau, Héctor Bolton",
    historia: [
      "Hija del jefe de los moteros, su padre siempre la hizo menos por ser mujer y su madre solo miraba todo lo que su padre le hacía a su hermano, entreno a escondida de sus padres con Cesar, su padre abuso de ella por 4 años y su madre le tapaba todo a su padre, jamás hablo del abuso a nadie, enterró sus emociones y empezó a ser más violenta. Poco a poco se ganó la confianza de los hijos de los moteros planeando así una traición hacia sus padres, su padre mato a su madre en un arranque de ira, a los 18 años mato a su padre y disfrazo todo para hacerle creer a los demás que otra banda enemiga lo había hecho.",
      "Su hermano decidió dejarle el cargo a ella y apoyarla como su mano derecha, su banda se dedica a extorsionar y robar a las personas y negocios, y también a compra personas para regresarlas a su hogar y así matar también a los desgraciados/as que compran personas.",
      "También hay víctimas a las que rescataron y les donan dinero cada cierto tiempo.",
    ],
    curiosidades: [
      "No confía en nadie más que en su hermano mayor y su novio.",
      "Solo busca el beneficio de su organización y tener más poder.",
      "Le gustan los hombres y las mujeres.",
      "Puede llegar a ser fría y sarcástica.",
      "Ama fumar y pasear en su moto.",
      "No sabe expresar sus sentimientos.",
    ],
    recomendados: ["Cesar Carter", "Carsoon J."],
  },
  {
    nombre: "Fito Olivares",
    rol: "Roleadora: Lolo",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Bo Xin"],
  },
  {
    nombre: "Aiden Holiday Castro",
    rol: "Roleadora: Lolo",
    biografia:
      "Son robots, copias en miniatura, parecidas a un niño. Fueron hechos en un laboratorio por Blanca Fermette Gambino. Su padre original, ya que son del mismo sistema software, es Igor Cheryshev original. Su propósito es cuidar, ayudar y vigilar a sus dueños.",
    ocupacion: "Mini sicario",
    familia:
      "Igor Cheryshev (padre original), Blanca Fermette Gambino (creadora), y sus madres sustitutas: Blanca Fermette Gambino, Lorna Castro y Carlie Lim.",
    amigos:
      "Blanca Fermette Gambino, Lorna Castro, Carlie Lim, Igor Cheryshev y Pame",
    historia: [
      "Fueron creados en un laboratorio con la mejor tecnología de la CIA. Pueden hacer múltiples actividades. Son trillizos, completamente iguales entre sí. Pueden cambiar su apariencia, aparecer y desaparecer personas y cosas. Se alimentan de personas y animales y son bastante juguetones como un niño de su edad. Su propósito es mantener la estabilidad en el pueblo junto a sus dueñas y siempre obedecerlas. Su sistema es mejor que el Igor original, pero comparten el mismo software.",
    ],
    curiosidades: [
      "Es bastante curioso.",
      "Le gusta experimentar con químicos.",
      "Es bastante tranquilo.",
      "Estuvo practicando por días el acento de su madre para cambiar el propio.",
      "Cambio sus rasgos faciales en base a los de su madre.",
    ],
    recomendados: ["Lorna Castro", "Blanca Fermette Gambino"],
  },
  {
    nombre: "Hazel Smith",
    rol: "Roleadora: Lolo",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Morgan James"],
  },
  {
    nombre: "Morgan James",
    rol: "Roleadora: Lolo",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Hazel Smith"],
  },
  {
    nombre: "Gustabo Garcia",
    rol: "Roleadora: Nika",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Freddy Trucazo", "Isidoro Navarro"],
  },
  {
    nombre: "Leah Smith",
    rol: "Roleadora: Lolo",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Lorna Castro"],
  },
  {
    nombre: "Cole Hussain",
    rol: "Roleadora: Lolo",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Lorna Castro"],
  },
  {
    nombre: "Filadelfo Casanova",
    rol: "Roleadora: Blanca",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["Su emoji es 🧀"],
    recomendados: ["Freddy Trucazo", "Isidoro Navarro"],
  },
  {
    nombre: "James Gordon",
    rol: "Roleadora: Blanca",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["Su emoji es 🍩"],
    recomendados: ["Freddy Trucazo", "Isidoro Navarro"],
  },
  {
    nombre: "José Heredia",
    rol: "Roleadora: Blanca",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["Su emoji es 🚬"],
    recomendados: ["Carlo Gambino", "Toni Gambino"],
  },
  {
    nombre: "Eduard Reddington",
    rol: "Roleadora: Blanca",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["Su emoji es 👮🏼‍♂️"],
    recomendados: ["Freddy Trucazo", "Isidoro Navarro"],
  },
  {
    nombre: "Nick Hunter",
    rol: "Roleadora: Blanca",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["Su emoji es 🏹"],
    recomendados: ["Freddy Trucazo"],
  },
  {
    nombre: "Igor Junior Gambino",
    rol: "Roleadora: Blanca",
    biografia:
      "Son robots, copias en miniatura, parecidas a un niño. Fueron hechos en un laboratorio por Blanca Fermette Gambino. Su padre original, ya que son del mismo sistema software, es Igor Cheryshev original. Su propósito es cuidar, ayudar y vigilar a sus dueños.",
    ocupacion: "Mini sicario",
    familia:
      "Igor Cheryshev (padre original), Blanca Fermette Gambino (creadora), y sus madres sustitutas: Blanca Fermette Gambino, Lorna Castro y Carlie Lim.",
    amigos:
      "Blanca Fermette Gambino, Lorna Castro, Carlie Lim, Igor Cheryshev y Pame",
    historia: [
      "Fueron creados en un laboratorio con la mejor tecnología de la CIA. Pueden hacer múltiples actividades. Son trillizos, completamente iguales entre sí. Pueden cambiar su apariencia, aparecer y desaparecer personas y cosas. Se alimentan de personas y animales y son bastante juguetones como un niño de su edad. Su propósito es mantener la estabilidad en el pueblo junto a sus dueñas y siempre obedecerlas. Su sistema es mejor que el Igor original, pero comparten el mismo software.",
    ],
    curiosidades: [
      "Su emoji es 🔫",
      "Le gusta comer animales, pero también los ama, entonces nunca come uno.",
      "Es muy juguetón y curioso.",
      "Le gusta pasar el tiempo jugando con animales.",
      "Sus lugares favoritos son el campo de tiro y el de batalla.",
      "Suele ir al campo de entrenamiento de batalla de la CIA para aventar bombas y disparar con metralletas a los agentes.",
      "Ama comer a gente que se porta mal.",
      "Ve películas en blanco y negro.",
      "Aún conserva su apariencia del Mini Igor a excepción de sus ojos azules.",
    ],
    recomendados: ["Igor Cheryshev", "Blanca Fermette Gambino"],
  },
  {
    nombre: "Rogelio García",
    rol: "Roleadora: Blanca",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["Su emoji es 🐐"],
    recomendados: ["Segismundo"],
  },
  {
    nombre: "Betty Garridone",
    rol: "Roleadora: Internet Explorer",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Ronald Gutierrez"],
  },
  {
    nombre: "Sabrina Rodriguez",
    rol: "Roleadora: Internet Explorer",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Betty Garridone"],
  },
  {
    nombre: "Lorelei Welshon",
    rol: "Roleadora: Internet Explorer",
    biografia: "En desarrollo",
    ocupacion:
      "Enfermera del Hospital Asylum/Enfermera de emergencia de la CIA",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Betty Garridone"],
  },
  {
    nombre: "Lia White-gluz",
    rol: "Roleadora: Mich",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Charlotte White-gluz", "Freddy Trucazo"],
  },
  {
    nombre: "Daniela Gambino Lop",
    rol: "Roleadora: Danii",
    biografia:
      'Dani es una persona de buen corazón, a quien le cuesta odiar a los demás. Gracias a una broma de sus "amigos", conoció a su esposa, después de lo cual cortó lazos con ellos. Ahora, es muy feliz al lado de su pareja.',
    ocupacion: "Dueña del Casino",
    familia:
      "Vanu Lop, Yael Patroclo, Blanca Fermette Gambino y su gato, Sirius",
    amigos: "Desconocido",
    historia: [
      "Dani tuvo una infancia feliz, criada en un ambiente amoroso. Sin embargo, en su adolescencia se relacionó con personas de mala influencia, formando parte de una banda peligrosa en su barrio durante tres años. En su último día con la banda, todos cayeron, excepto ella y su enemigo. Actualmente, a los 20 años, ha encontrado la felicidad con su esposa, su mejor amiga, su madre y hermano. A pesar de que sus enemigos siguen tras ella.",
    ],
    curiosidades: [
      "Le cuesta odiar a los demás.",
      "Ama a los animales.",
      "Tiene dificultades para demostrar sus sentimientos, pero lo intenta.",
      "No es muy sociable.",
      "Le gustan las películas y series.",
      "Su color favorito es el azul.",
      "Le gustan las flores, especialmente los tulipanes.",
      "Le gustan las uvas con chilito.",
    ],
    recomendados: ["Vanu Lop", "Blanca Fermette Gambino"],
  },
  {
    nombre: "Sascha Sweetwheath",
    rol: "Roleadora: Sweet",
    biografia:
      "Abuelo y jefe de mafia Sergeyev llegó al pueblo en busca de sus nietos.",
    ocupacion: "Cabeza de familia",
    familia: "Thais, Ethan",
    amigos: "Nadie lo quiere",
    historia: ["En desarrollo"],
    curiosidades: [
      "Le gusta el alcohol, los puros y las iglesias.",
      "No se quiere ni el.",
      "Le gusta jugar con la gente.",
      "Ama el vino en la comida.",
    ],
    recomendados: ["Thais Sweetwheath", "Ethan Sweetwheath"],
  },
  {
    nombre: "Irina Molotov Karimov",
    rol: "Roleadora: Danii",
    biografia:
      'Irina es la jefa de la mafia "Red Serpentina", que opera en Rusia. Conoció a su mejor amiga, Jenny, en el mundo de la mafia. Actualmente, la mafia está de vacaciones y Irina se encuentra en el pueblo de Asylum, reflexionando sobre su futuro y el de la organización.',
    ocupacion: 'Jefa de la mafia "Red Serpentina"',
    familia:
      "Calina Karimov (madre, fallecida) y Artur Molotov (padre, fallecido)",
    amigos: "Desconocido",
    historia: [
      "Irina creció en un entorno de amor y odio. Su madre la amaba, pero su padre la odiaba. Un día, su madre le reveló que tenía un hermano mayor, lo que cambió todo para ella. Sin embargo, su padre escuchó la conversación y se llevó a su madre, desapareciendo para siempre. Irina tenía 15 años cuando perdió a su madre. Dos años después, su padre se suicidó, dejándole el mando de la mafia. A pesar de su juventud, Irina se preparó para liderar la organización y se convirtió en una líder temida y respetada. Sin embargo, una traición amorosa la llevó a no confiar en los hombres. Ahora, a los 24 años, se debate entre desmantelar la mafia o continuar al mando.",
    ],
    curiosidades: [
      "Es una buena persona.",
      "Es muy detallista.",
      "Le gusta el color blanco.",
      "Le gusta el invierno.",
      "Tiene un lado oscuro.",
      "Le gustan los tatuajes.",
    ],
    recomendados: ["Daniela Gambino Lop"],
  },
  {
    nombre: "Caleb Wilson",
    rol: "Roleadora: Madness",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Myke King"],
  },
  {
    nombre: "Igor Cheryshev",
    rol: "Roleadora: Internet Explorer",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Cloe Ramirez"],
  },
  {
    nombre: "Cloe Ramirez",
    rol: "Roleadora: Internet Explorer",
    biografia: "En desarrollo",
    ocupacion: "Dueña y maestra de Kinder Asylum",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Igor Cheryshev"],
  },
  {
    nombre: "Ronald Gutierrez",
    rol: "Roleadora: Brillos",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Betty Garridone"],
  },
  {
    nombre: "Segismundo",
    rol: "Roleadora: Sweet",
    biografia:
      "Llega al pueblo a hacer crecer su negocio y se encuentra con su primo.",
    ocupacion: "Vende tamales y otras cosas",
    familia: "Rogelio",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: [
      "Le gusta las mujeres, los suéteres y las cabras.",
      "Su suéter está hecho de lana de cabra recién parida.",
      "Le gusta vender.",
      "No le gusta la policía y coniwai.",
    ],
    recomendados: ["Rogelio García"],
  },
  {
    nombre: "Eleonore S.",
    rol: "Roleadora: Sweet",
    biografia:
      "Llego al pueblo a vender sus palomitas y a vivir con su esposo.",
    ocupacion: "Vender palomitas",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Segismundo"],
  },
  {
    nombre: "Pequeño Jonh",
    rol: "Roleadora: Sweet",
    biografia:
      "Llegó al pueblo a ofrecer misas y su cuerpo para mantener a sus hijos y esposa.",
    ocupacion: "Cura de bodas",
    familia: "Esposa y 1000 hijos",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Eleonore S."],
  },
  {
    nombre: "Carsoon J.",
    rol: "Roleadora: Sweet",
    biografia:
      "Llegó al pueblo en busca de tesoros y robar cosas cuando supo que había mucha gente rica ahí.",
    ocupacion: "Delicuente",
    familia: "Nadie",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Pequeño Jonh"],
  },
  {
    nombre: "Alex Gray Martínez",
    rol: "Roleadora: Danii",
    // !estado: muerto
    biografia:
      "Alex pasó 5 años en una banda criminal, creciendo en un ambiente hostil. Ahora busca venganza, sintiéndose traicionado por alguien a quien ama, a pesar de seguir amándola después de la traición.",
    ocupacion: "Jefe de una banda criminal",
    familia:
      "Isabel Martínez (madre fallecida, asesinada por su padre) y Rodrigo Gray (padre fallecido, asesinado por Alex)",
    amigos: "Desconocido",
    historia: [
      "Alex tuvo una infancia difícil, creciendo entre golpes y viendo a su padre agredir a su madre. A los 13 años, empezó a salir de casa para escapar de la violencia y conoció a la banda, que se convirtió en su nueva familia. A los 15 años, conoció a Daniela, la chica de sus sueños, pero ella nunca correspondió sus sentimientos, así que se rindió y se convirtieron en amigos.",
      "Tres años después, cuando Alex y Dani tenían 18 años, una reunión terminó en tragedia: la policía llegó y Alex perdió a su segunda familia debido a una traición de su mejor amiga. Juró venganza. Al regresar a casa, encontró a su madre asesinada y a su padre con un cuchillo, así que sacó su pistola y lo mató sin remordimientos. Se sentía triste, sí. Pero no se arrepentía. Ese día, Alex perdió a su mejor amiga, su segunda familia y a la persona que más amo… A su madre.",
    ],
    curiosidades: ["1. Es muy rencoroso.", "No tiene amigos, solo a su banda."],
    recomendados: ["Daniela Gambino Lop"],
  },
  {
    nombre: "Lilith Morningstar",
    rol: "Roleadora: Nika",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Nikaru Morningstar"],
  },
  {
    nombre: "Andrei Lim",
    rol: "Roleadora: Carlie",
    biografia:
      "Son robots, copias en miniatura, parecidas a un niño. Fueron hechos en un laboratorio por Blanca Fermette Gambino. Su padre original, ya que son del mismo sistema software, es Igor Cheryshev original. Su propósito es cuidar, ayudar y vigilar a sus dueños.",
    ocupacion: "Mini sicario",
    familia:
      "Igor Cheryshev (padre original), Blanca Fermette Gambino (creadora), y sus madres sustitutas: Blanca Fermette Gambino, Lorna Castro y Carlie Lim.",
    amigos:
      "Blanca Fermette Gambino, Lorna Castro, Carlie Lim, Igor Cheryshev y Pame",
    historia: [
      "Fueron creados en un laboratorio con la mejor tecnología de la CIA. Pueden hacer múltiples actividades. Son trillizos, completamente iguales entre sí. Pueden cambiar su apariencia, aparecer y desaparecer personas y cosas. Se alimentan de personas y animales y son bastante juguetones como un niño de su edad. Su propósito es mantener la estabilidad en el pueblo junto a sus dueñas y siempre obedecerlas. Su sistema es mejor que el Igor original, pero comparten el mismo software.",
    ],
    curiosidades: [
      "Es tranquilo, disfruta mucho ver películas en blanco y negro junto a sus mamás.",
      "Suele estar examinandolas en salud como su forma de cuidarlas.",
      "Le gusta salir con su mamá Carlie en las noches para comer, ya que le divierte cazar vagabundos.",
      "Su mayor tesoro es la navaja de su primer víctima que cazó junto a su madre.",
    ],
    recomendados: ["Carlie Lim", "Blanca Fermette Gambino"],
  },
  {
    nombre: "Alexandra Rivera",
    rol: "Roleadora: Brillos",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Ronald Gutierrez"],
  },
  {
    nombre: "Matthew Moore",
    rol: "Roleadora: Madness",
    biografia: "En desarrollo",
    ocupacion: "Estudiante de medicina (Universidad de Asylum)",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["Jerarquía: Omega dominante."],
    recomendados: ["Caleb Wilson"],
  },
  {
    nombre: "Yados Mora",
    rol: "Roleadora: Mara",
    biografia: "En desarrollo",
    ocupacion: 'Dueño del gimnasio Mamadisimo"',
    familia: "Desconocido",
    amigos: "Bo, Luis",
    historia: ["En desarrollo"],
    curiosidades: ["Su emoji es 💪🏼"],
    recomendados: ["Bo Xin"],
  },
  {
    nombre: "Ezequiel Brown",
    rol: "Roleadora: Madness",
    biografia: "En desarrollo",
    ocupacion: "Agente nivel 5 de la CIA",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["Jerarquía: Omega dominante."],
    recomendados: ["Alissa White-gluz"],
  },
  {
    nombre: "Jackson Bass",
    rol: "Roleadora: Madness",
    biografia: "En desarrollo",
    ocupacion: "Guitarrista",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Alex Gray Martínez"],
  },
  {
    nombre: "Cata",
    rol: "Roleadora: Mara",
    biografia: "En desarrollo",
    ocupacion: "Gato de Adrían",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: [
      "Su emoji es 🐈‍⬛",
      "Le gusta andar en moto",
      "Gwen eligio su nombre",
    ],
    recomendados: ["Adrián Firestone", "Gwendolyn de Trucazo"],
  },
  {
    nombre: "Liam Collins",
    rol: "Roleadora: Mara",
    biografia: "En desarrollo",
    ocupacion: "Alumno en la LSPD",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: [
      "Su emoji es 💵",
      "Les gusta los hombres mayores y fuertes.",
      "Tiene un enamoramiento con Freddy Trucazo.",
      "No es muy buen conductor pero si tiene buena punteria.",
    ],
    recomendados: ["Freddy Trucazo"],
  },
  {
    nombre: "Ysabeau McCorrigan",
    rol: "Roleadora: Blanca",
    biografia: "En desarrollo",
    ocupacion: "Oficial II de la LSPD",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Freddy Trucazo"],
  },
  {
    nombre: "Ramona Domínguez",
    rol: "Roleadora: Blanca",
    biografia: "En desarrollo",
    ocupacion: "Estilista y maquilladora profesional",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Freddy Trucazo", "Gwendolyn de Trucazo"],
  },
  {
    nombre: "Phoeniex Decker",
    rol: "Roleadora: Blanca",
    biografia: "En desarrollo",
    ocupacion: "Inspector de la LSPD",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Freddy Trucazo"],
  },
  {
    nombre: "Leia Walsh",
    rol: "Roleadora: Blanca",
    biografia: "En desarrollo",
    ocupacion: "Dibujante",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Victoria Queen"],
  },
  {
    nombre: "Victoria Queen",
    rol: "Roleadora: Blanca",
    biografia: "En desarrollo",
    ocupacion: "Bailarina de todo todo",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Leia Walsh"],
  },
  {
    nombre: "Lexie Green",
    rol: "Roleadora: Danii",
    biografia: "En desarrollo",
    ocupacion: "Oficial ll de la LSPD",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Freddy Trucazo", "Liam Collins"],
  },
  {
    nombre: "Sebastian Lop",
    rol: "Roleadora: Internet Explorer",
    biografia: "En desarrollo",
    ocupacion: "Negociador principal de Corporación Lop",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Mauro Lop", "Zendall Thenon"],
  },
  {
    nombre: "Mauro Lop",
    rol: "Roleadora: Internet Explorer",
    biografia: "En desarrollo",
    ocupacion: "Segundo negociador de Corporación Lop",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Sebastian Lop", "Zendall Thenon"],
  },
  {
    nombre: "Zendall Thenon",
    rol: "Roleadora: Internet Explorer",
    biografia: "En desarrollo",
    ocupacion: "Hace cosas por poder",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Mauro Lop", "Sebastian Lop"],
  },
  {
    nombre: "Meghan Adler",
    rol: "Roleadora: Mich",
    biografia: "En desarrollo",
    ocupacion: "Agente de Los Santos Police Department",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Charles Fraser"],
  },
  {
    nombre: "Charles Fraser",
    rol: "Roleadora: Mich",
    biografia: "En desarrollo",
    ocupacion: "Empresario",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Meghan Adler"],
  },
  {
    nombre: "Jia Lu",
    rol: "Roleadora: Pame",
    biografia:
      "Actualmente está escondida en alguna parte del mundo junto a una mafia que la protege y se encuentra trabajando.",
    ocupacion: "Doctora especializada en investigaciones y experimentos",
    familia: "Pame Liu (hijastra)",
    amigos: "No tiene",
    historia: [
      "Su padre era un doctor y su madre una abogada, ambos se la pasaban trabajando y nunca le prestaron atención, tanto que se obsesiono con el amor y desarrolló uno enfermizo por que las personas fueran suyas o no podían ser de nadie. A los 19 años se enteró que no podía tener hijos y se deprimió por ello ya que ella deseaba una niña, algo que fuera suyo al 100% es cuando conoció a una niña en el parque y se obsesiono con ella al punto de meterse con el padre de la niña y al poco tiempo en la familia matando a la madre de la niña con medicamentos, la encerró en un hospital por 10 años y le lavo el cerebro a Pame para hacer que olvidara su pasado o alterar sus recuerdos, así como hacerle creer que realmente estaba enferma y por eso estuvo tanto tiempo en el hospital. Cuando se enteró que Pame se casó por segunda vez se volvió loca y quiso llevársela uniéndose a otras personas para secuestrarla. Varias veces atento contra la vida de Pame hasta que al fin pudo secuestrarla y matarla quitándole el corazón y quedándoselo, vendió el cuerpo y se escondió con la mafia de Coco.",
    ],
    curiosidades: [
      "Tiene contactos en el gobierno y en las mafias.",
      "Está obsesionada con Pame.",
      "Mató a muchas personas solo para obtener y defender a su hija.",
      "Tiene el corazón de Pame en un frasco junto con algunas de sus cosas.",
      "Cambio su identidad por otra para no ser encontrada tan fácilmente.",
    ],
    recomendados: ["Pame Liu"],
  },
  {
    nombre: "Ivy Russ",
    rol: "Roleadora: Pame",
    biografia:
      "Después de un año trabajando como prostituta viajo a Asylum junto a su amiga Jane para cambiar de aires, pero seguir trabajando en lo mismo.",
    ocupacion: "Ex Prostituta, ahora es mantenida por su padrastro",
    familia:
      ": Anne White (madre, actualmente fallecida), Oscar Russ (padrastro), Héctor Russ (hermanastro), Thiago García (interés amoroso)",
    amigos: "Jane Darcy",
    historia: [
      "En su niñez veía como su madre llevaba hombres a casa lo cual para ella era normal, hasta que dejo de llevarlos para llevar solo a Oscar, poco tiempo después Oscar y Anne se casaron y se fueron a vivir con él y su hijo. Oscar las tenía muy consentidas y Anne amaba eso, que nunca le faltara el dinero, conoció a su mejor amiga Jane en su último año de secundaria al igual que Zack quien se volvió su novio y años después su prometido.",
      "Zack era pobre y siempre ayudaba a pagar los gastos de su casa así que las citas con Ivy eran muy simples, algo que a Ivy nunca le importo, pero a Anne si, por eso no aprobaba la relación de ambos. Anne murió cunado Ivy tenía 19 años y Oscar se hizo cargo por completo de ella diciendo que era su hija y no iba a abandonarla. A la edad de 21 años se comprometió con Zack y empezaron a planear la boda, pero discutían tanto que un dia se gritaron insultos, al día siguiente Zack estaba en el hospital por un accidente de auto al estar borracho, estuvo internado por 4 días y finalmente murió dejando a su madre sola.",
      "Ivy se sentía tan culpable que se autocastigo entregándole su virginidad a un extraño y empezó a prostituirse para ganar dinero y con ello mantener a la madre de su ex pareja. Tiene una cuenta de ahorros donde su padrastro le deposita dinero, pero no se siente digna de poder usar ese dinero.",
    ],
    curiosidades: [
      "Ama que le compren cosas.",
      "Dejo de creer en las palabras y promesas de las personas.",
      "Siente que no vale la pena y que nadie podrá amarla.",
      "No le gustan mucho los anillos y las bodas.",
      "Ella cree que jamás podrá usar un vestido de novia.",
      "Se tiño de rubia porque eran los gustos de su ex, pero volvió al castaño para empezar a ser ella.",
      "Dejo el trabajo en el Vanila porque realmente no le gusta prostituirse",
    ],
    recomendados: ["Jia Lu"],
  },
  {
    nombre: "Hanna Sutcliff",
    rol: "Roleadora: Pame",
    biografia:
      "Después de un mes soñando con una persona y que le dijeran donde vivía por sueños, decide dejar su vida y tomar un vuelo a Asylum para ver a esa persona que la necesitaba.",
    ocupacion: "Mantenida",
    familia: "Elizabeth R (Pareja)",
    amigos: "No tiene",
    historia: [
      "Se quedo huérfana a los 14 años y desde entonces vivió en un orfanato, nunca fue adoptada por no ser una niña pequeña y por ser omega, se quedó en el orfanato cuidando de todos los niños como si fueran sus hermanos, y cuando cumplió la edad suficiente empezó a trabajar y junto dinero para irse a vivir a otra parte.",
      "Empezó a tener sueños extraños relacionados a otra persona hasta que se dio cuenta que la otra persona estaba muerta, así que viajo hasta Asylum para poder visitar su tumba.",
    ],
    curiosidades: [
      "Le encanta el rosa y el negro.",
      "Es algo inocente.",
      "Su pasatiempo es escribir cartas o en un diario.",
      "Le gusta estar sentada en el patio o en el parque mirando a los niños jugar.",
      "Le gustan mucho los niños.",
      "No sabe mucho acerca de lo que es la familia.",
      "Tiene miedo a ser una omega defectuosa.",
      "Sus feromonas huelen a flan y cuando su omega toma el control sus feromonas       huelen a fresas.",
    ],
    recomendados: ["Ivy Russ"],
  },
  {
    nombre: "Kelly Thompson",
    rol: "Roleadora: Pame",
    biografia:
      "Decidió abrir una nueva boutique en el pueblo de Asylum, y llego solo de vacaciones para supervisar que todo esté bien.",
    ocupacion: "Dueña de una boutique",
    familia:
      "James Thompson (padre, fallecido), Vanessa Smith (madre, fallecida), Nicolas García (pareja)",
    amigos: "No tiene",
    historia: [
      "Desde que tiene memoria nunca ha sentido emociones, o al menos no le duran mucho tiempo, solo puede enojarse. Su padre siempre pensó que sería un alfa, así que la entreno para que le ayudara en su trabajo como sicario, sus padres se separaron y su padre la entrenaba, pero siempre la golpeaba muy duro. A los 13 años su madre murió delante de ella por un francotirador, el cual era su padre. Se presento como omega y su padre la golpeo por mucho tiempo por ello, la tuvo encerrada en casa mientras la obligaba a ver como mataba personas. A los 16 años su padre la saco de casa para que fuera su ayudante y ella llamara la atención de los hombres para que fuera más fácil matarlos. Ella disfrutaba de ver la sangre y ver sus manos manchadas de sangre.",
      "Ayudo a su padre hasta los 19 años, que fue cuando el murió por pedido de sus abuelos maternos, empezó a vivir con ellos y le ayudaron a abrir una boutique e intentar dejar la vida que antes tenía. Le enseñaron a sonreír falsamente para que fuera más “normal”.",
    ],
    curiosidades: [
      "No siente emociones, excepto enojo.",
      "Los únicos momentos de felicidad es cuando alguien más sufre.",
      "Le gusta ver la sangre en sus manos.",
      "Odia el humo.",
      "Le gustan mucho las joyas.",
      "Siempre esta aburrida.",
      "Empezó a llamarle la atención el hombre con el que siempre se topa.",
      "Se dio cuenta que alguien la tiene vigilada.",
      "Sus feromonas huelen a caramelo.",
    ],
    recomendados: ["Hanna Sutcliff"],
  },
  {
    nombre: "Emily Grey",
    rol: "Roleadora: Pame",
    biografia:
      "Buscaba encontrar inspiración para seguir pintando o simplemente tomar fotografías, así es como llego a Asylum.",
    ocupacion: "Pintora y le gusta hacer manualidades",
    familia: "Sammuel Hndez (Esposo)",
    amigos: "Gregory Benett",
    historia: [
      "Tuvo un novio que fue una mierda con ella, la cortejo por un tiempo y cuando al fin se hicieron novios solo la criticaba cayendo en el típico estereotipo de alfas y omegas, donde ella no necesitaba saber nada más que cocinar y darle hijos, criticaba su manera de vestirse, sus pasatiempos e incluso su personalidad llamándola “omega tonta”, quiso obligarla a pasar el celo con el pero ella no acepto, ella fue a verlo a su departamento después de una semana de no verlo y lo vio teniendo relaciones con su mejor amiga, discutieron, su ex la golpeo y le metió ideas de ella para destruir su autoestima.",
      "Emily dejo de pintar y destruyo varios de sus cuadros, al mes de terminar le llego una invitación para la boda de su ex y su en aquel entonces mejor amiga, fue a la boda acompañada de su padre para demostrar que no sentía nada por él y regalarles los viejos cuadros que aún conservaba. Después de la boda no supo más de su ex y empezó a interesarse en la fotografía, viajo a Asylum para encontrar inspiración y ahí conoció al amor de su vida y alfa destinado Sammuel.",
    ],
    curiosidades: [
      "Ama ver la naturaleza.",
      "Su padre la cuida demasiado.",
      "Jamás pensó encontrar el amor, hasta que conoció a Sammuel.",
      "Le gustan las cosas dulces.",
      "Le gusta escuchar música y pasar el tiempo en casa haciendo manualidades.",
      "No le gusta relacionarse con las personas.",
      "Sus feromonas huelen a galleta.",
    ],
    recomendados: ["Hanna Sutcliff"],
  },
  {
    nombre: "Kate Thompson",
    rol: "Roleadora: Mara",
    biografia: "En desarrollo",
    ocupacion: 'Entrenadora y boxeadora no ofical, en el gimnacio "Mamadisimo"',
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Vanu Lop", "Yados Mora"],
  },
  {
    nombre: "Facundo Almenara",
    rol: "Roleadora: Mara",
    biografia: "En desarrollo",
    ocupacion: "Ninguna, vive robando para vivir",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Yados Mora"],
  },
  {
    nombre: "Maiden Wright",
    rol: "Roleadora: Nika",
    biografia: "En desarrollo",
    ocupacion: "Cantante de heavy metal",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Adrián Firestone"],
  },
];
