let roleadores = [
  {
    nombre: "Mara",
    personajes: [
      "Adrián Firestone",
      "Sarah Firestone",
      "Isidoro Navarro",
      "Mei Feng",
    ],
  },
  {
    nombre: "Sweet",
    personajes: ["Thais Sweetwheath", "Shariel S.", "Ethan Sweetwheath"],
  },
  {
    nombre: "Mich",
    personajes: [
      "Samantha Anderson",
      "Michelle Byron de Sweetheath",
      "Harper Byron",
      "Dianna Evans",
    ],
  },
  {
    nombre: "Lolo",
    personajes: ["Lorna Castro", "Agente X", "Bo Xin"],
  },
  {
    nombre: "Blanca",
    personajes: ["Blanca Fermette Gambino", "Freddy Trucazo", "Toni Gambino"],
  },
  {
    nombre: "Internet Explorer",
    personajes: ["Vanu Lop"],
  },
  {
    nombre: "Wen",
    personajes: [
      "Wernobyl Trucazo",
      "Jennifer King",
      "Elijah Müller",
      "Myke King",
    ],
  },
  {
    nombre: "Brillos",
    personajes: ["Brillith Torres"],
  },
  {
    nombre: "Carlie",
    personajes: [
      "Jasha Volkov",
      "Carlo Gambino",
      "Carlie Lim",
      "Maxim Zaitsev",
    ],
  },
  {
    nombre: "Madness",
    personajes: [
      "Bianca Madison Johnson",
      "Charlotte White-gluz",
      "Laoviah",
      "Milagros Johnson",
    ],
  },
  {
    nombre: "Nika",
    personajes: ["Nikaru Morningstar", "Alissa White-gluz"],
  },
];

let personajes = [
  {
    nombre: "Adrián Firestone",
    rol: "Roleadora: Mara",
    biografia:
      "Llego a Asylum cuando se entero que su hermana, Sarah, fue ingresada al hospital por una sobredosis. Trabaja para los Sweet Dreams, le encanta disfrutar del momento y es un putero nato.",
    ocupacion: "Miembro de los Sweet Dreams",
    familia: "Sarah (hermana)",
    amigos: "Isidoro, Bo, Luis",
    historia: [
      "El y su hermana gemela nacieron en Argentina pero a una edad muy joven su padre los llevó a Los Santos para tener una mejor vida, pero pronto ambos fueron abandonados a su suerte por este. Los gemelos lograron sobrevivir trabajando desde jóvenes para maleantes, hasta que ambos se separaron por una pelea.",
      "Adrián se fue a vivir a Marbella, donde conoció a Bo en una carrera inlegal, donde este le ayudo a escapar de la policia. Desde entonces trabaja para él y se hizo gran amigo de este y varios integrantes de la banda.",
    ],
    curiosidades: [
      "Es muy protector con su hermana.",
      "Conoce a Isidoro desde jóvenes, antes de que este ingresara a la CIA. Mantuvieron la amistad a pesar de que tomaron caminos opuestos.",
      "Le gusta coquetear con mujeres, sobre todo casadas, ya que le gusta el desafío.",
      "Es muy leal, aunque suele ser despreocupado con sus relaciones amorosas.",
      "No le gustan los mariscos ni la policía.",
      "Después de que un hombre enmascarado de toro lo atacara y lo dejara gravemente lastimado, generó una fobia hacia los toros.",
    ],
    recomendados: ["Sarah Firestone", "Isidoro Navarro"],
  },
  {
    nombre: "Sarah Firestone",
    rol: "Roleadora: Mara",
    biografia:
      "Después de que su esposa le pidiera el divorció, tiene una sobredosis y queda en coma por un tiempo. Al final despierta, pero tiene perdida de memoria, olvidándose de su mujer y todo lo vivido en el pueblo.",
    ocupacion: "Desconocido",
    familia: "Adrián (hermano)",
    amigos: "Isidoro, desconocido",
    historia: [
      "El y su hermana gemela nacieron en Argentina pero a una edad muy joven su padre los llevó a Los Santos para tener una mejor vida, pero pronto ambos fueron abandonados a su suerte por este. Los gemelos lograron sobrevivir trabajando desde jóvenes para maleantes, hasta que ambos se separaron por una pelea.",
      "Sarah fue militar pero fue echada del cuerpo luego de agredir a un superior, quemandole el rostro. Se caso al poco tiempo de llegar a Asylum, pero luego de ser atrapada coqueteando con otras mujeres, su esposa le pide el divorcio y aborta el hijo que estaban esperando.",
    ],
    curiosidades: [
      "Le gusta los animales y el fuego (es pirómana).",
      "Conoce a Isidoro desde que eran jóvenes gracias a su hermano, lo considera como su segundo hermano.",
      "No entiende porque le gustaba ir a misa estando en Asylum, ya que nunca fue una persona religiosa.",
      "No le gustan los hombres ni aprueba que su hermano siga involuncrado con las ventas de drogas.",
      "Es una persona solitaria y guarda muchos secretos.",
    ],
    recomendados: ["Adrián Firestone", "Isidoro Navarro"],
  },
  {
    nombre: "Isidoro Navarro",
    rol: "Roleadora: Mara",
    biografia:
      "Luego de un suceso que no recuerda, fue despedido del cuerpo y encomendada la misión, por parte de la CIA, de infiltrarse en los Sweet Dreams.",
    ocupacion: "Agente de la CIA",
    familia: "Desconocido",
    amigos: "Gustabo, Adrián, Sarah",
    historia: ["En desarrollo"],
    curiosidades: [
      "Su nombre original es Gonzalo, cambiado por la CIA. Los unicos que conocen su pasado son Adrián y Sarah.",
      "Le encanta salir con muchas mujeres, agenda a cada una como Chica enumerandolas. Pero su Chica numero 1 siempre sera Gustabo.",
      "Conocio a Adrián y a su hermana en las calles, cuando era joven y sobrevivia haciendo trabajos varios.",
      "Su sueño siempre fue trabajar como policia y finalmente, después de años no solo fue contratado en el cuerpo, sino como agente de la CIA.",
      "Desde la desaparición de Gustabo, Isidoro no ha parado de buscarlo.",
    ],
    recomendados: ["Adrián Firestone", "Sarah Firestone"],
  },
  {
    nombre: "Thais Sweetwheath",
    rol: "Roleadora: Sweet",
    biografia:
      "Llegó a Asylum cuando su abuelo la nombró sucesora de la familia/mafia y llegó al pueblo a hacer negocios.",
    ocupacion: "Mafia Sergeyev",
    familia: "Michelle, Harper y Ethan",
    amigos: "Shariel",
    historia: [
      "Fue criada por su abuelo y hermana gemela después de presenciar el suicidio de su madre, tuvo múltiples entrenamiento y misiones donde vio morir a tanta gente que ahora no le toma tanta importancia a las vidas de sus agentes.",
      "Cuando la nombraron Sasha de la mafia creo una facción externa para atacar a su abuelo, en esa facción de reencontró con Shariel la que fue su prometida cuando eran niñas.",
    ],
    curiosidades: [
      "Tiene un amor obsesivo por su esposa y solo ella le importa.",
      "Le gusta su esposa y el cacahuete.",
      "No le gusta que toquen a su esposa y el chocolate.",
      "Su fuente de alimentos se basa en whisky y cacahuates.",
      "Su pasatiempo preferido es estar con su esposa.",
      "Cuando se molesta comienza a hablar en ruso.",
      "Le gusta ver cómo Ethan se divierte asesinando gente",
    ],
    recomendados: ["Shariel S.", "Ethan Sweetwheath"],
  },
  {
    nombre: "Ethan Sweetwheath",
    rol: "Roleadora: Sweet",
    biografia:
      "Su abuelo lo quería matar pero lo robo Shariel y lo llevo a Asylum con su tía Thais para que lo cuide. Es el segundo heredero de la mafia.",
    ocupacion: "Mafia Sergeyev",
    familia: "Thais, Michelle y Harper",
    amigos: "No tiene",
    historia: [
      "Hijo de la hermana gemela de Thais, pensaron que era niña y su abuelo lo acogió, cuando descubrieron que era niño lo abandono en un sótano sin comida para que muriera.",
      "Shariel lo rescata y se lo entrega a la familia Byron Sweetwheath para que cuiden de el ahí conoció a su mamá y su hermano mayor.",
    ],
    curiosidades: [
      "Le gusta sus mamás, su hermano y los cacahuetes.",
      "No le gusta que lo lastimen y el chocolate.",
      "Imita al 100% a Thais cuando trabajan y le gusta salir con ella.",
      "Su pasatiempo preferido es matar gente pero prefiere quedarse con su familia.",
      "Cuando habla o le dice algún secreto a  Thais lo hace en ruso.",
      "Le gusta amenazar a sus empleados.",
    ],
    recomendados: ["Thais Sweetwheath", "Shariel S."],
  },
  {
    nombre: "Shariel S.",
    rol: "Roleadora: Sweet",
    biografia:
      "Mano derecha de Thais, se hace cargo de mover merca en el pueblo y ahora se hace cargo completamente del negocio en el pueblo.",
    ocupacion: "Mano derecha de la Sasha",
    familia: "Mikhail (muerto)",
    amigos: "Thais",
    historia: ["En desarrollo."],
    curiosidades: [
      "Le gusta el coito ,el chocolate y puchula.",
      "No le gusta la religión y las dagas.",
      "Es muy tímida cuando alguien le gusta.",
      "Le encanta asesinar a la gente en el coito.",
      "No le gusta hablar en ruso.",
      "Solo come pasteles y Malteadas.",
    ],
    recomendados: ["Thais Sweetwheath", "Ethan Sweetwheath"],
  },
  {
    nombre: "Samantha Anderson",
    rol: "Roleadora: Mich",
    biografia:
      "Vuelve a Asylum después de la muerte de su pareja Jace en Nueva Orleans, consigue trabajo en el hospital y se queda viviendo una vida relativamente tranquila, le encanta su trabajo y también cocinar.",
    ocupacion: "Enfermera en el hospital de Asylum",
    familia: "Grace y Henry Anderson",
    amigos: "Sherlyn Knox (muerta)",
    historia: [
      "Nace en Asylum y vive ahí la mayor parte de su vida hasta que decide mudarse para ir a estudiar a la universidad de nueva Orleans, ahí conoce a Jace que después de unos meses le pide ser su novia, continúan siendo pareja hasta que un fatídico día ocurre un robo a el apartamento de su novio donde las cosas salen mal dejándola con una herida de bala y a Jace muerto.",
      "Al pasar de los años sufre de depresión severa y ansiedad, sus padres la convencen de regresar a el pueblo y de ahí comienza a mejorar y superar la muerte de Jace, desde que regresa comienza a volver a amar su profesión y a tratar de disfrutar la vida.",
    ],
    curiosidades: [
      "Le gusta los postres dulces, cocinar, hablar con los pacientes y ayudar a las personas.",
      "No le ver a gente que le importa herida ni recordar el pasado.",
      "Después de el accidente su mano derecha comenzó a temblar cada vez que esta nerviosa o preocupada.",
      "Es alérgica a las nueces.",
      "Carga un dije con ella desde hace varios años.",
      "Es hija única.",
      "Se le es difícil conocer gente nueva y abrirse a las personas.",
    ],
    recomendados: ["Thais Sweetwheath", "Ethan Sweetwheath"],
  },
  {
    nombre: "Michelle Byron de Sweetheath",
    rol: "Roleadora: Mich",
    biografia:
      "Llega a asylum para tomar un largo descanso después de su última misión exitosa, esta casada con Thais sweetheart y tiene dos hijos, solo está en casa o con su esposa, le gusta divertirse y salir a beber pero casi no lo hace.",
    ocupacion: "En descanso de misiones militares",
    familia: "Harper Byron (hermano)",
    amigos: "Pame y Bitter (ella las considera)",
    historia: [
      "Su hermano y ella nacen en Londres Inglaterra donde cuando ambos eran adolescentes sufren la pérdida de ambos padres, duraron en Londres juntos hasta la muerte de su adorado hermano Harper el cual fue dado muerto a la edad de  18 años dejando así a una Michelle de tan solo 16 años sola.",
      "El quedarse sola la lleva a enlistarse en un tipo escuadrón militar durando así 6 años en combate y misiones al terminar el último año decide tomar un descanso y termina en asylum donde conoce a su ex esposa y esposa actual, después del nacimiento de su hijo deciden irse a vivir a Londres donde ahora sigue viviendo felizmente con su familia.",
    ],
    curiosidades: [
      "Le gusta su esposa, cuidar de sus hijos, combates cuerpo a cuerpo y el chocolate.",
      "No le gusta consumir cosas muy saladas, no ver a sus hijos o esposa.",
      "Después de la muerte de su hermano olvidó gran parte de su vida.",
      "Tuvo dos parejas en su estancia como militar.",
      "Es fiel, sentimental, es algo indiferente cuando se trata de personas que no significan nada para ella.",
    ],
    recomendados: ["Harper Byron", "Dianna Evans"],
  },
  {
    nombre: "Harper Byron",
    rol: "Roleadora: Mich",
    biografia:
      "Nace en Londres y vive la mayor parte de su vida ahí, perdió gran parte de su vida al estar en coma, al despertar descubre que fue dado por muerto y su hermana abandonó la ciudad donde crecieron ambos y decide esperar a que vuelva.",
    ocupacion: "Asesino a sueldo",
    familia: "Michelle Byron, Alexander y Alison Byron (muertos)",
    amigos: "Sin amigos",
    historia: [
      "Junto a su hermana nace y crece en Londres donde al nacer su hermana se vuelve como una figura paterna para ella y se encarga de cuidarla.",
      "Sufrió de varios abusos por parte de sus padres y recibió cada castigo que iba para su hermana ya que no quería que ella sufriera, después de la muerte de sus padres entra en conflicto en su mente lo cual lo lleva a querer terminar con su vida de ahí termina en coma durante algunos años, al descubrir que su hermana piensa que murió decide no enfrentarla ya que sabe que eso la dañaría de una forma que se prometió nunca hacerla sufrir, después de despertar se convierte en asesino a sueldo para llevar una vida decente.",
    ],
    curiosidades: [
      "Se dedica a observar a su hermana la mayor parte de su tiempo ya que la extraña demasiado.",
      "Le gusta el chocolate, los hombres  y cuidar a su hermana.",
      "No le gusta ver triste a su hermana y lo saldo.",
      "La frase que lleva consigo es ama con toda el alma.",
      "La frase que lleva consigo es ama con toda el alma.",
      "Es muy leal y amistoso.",
      "Le gusta cuidar a la gente que le importa",
    ],
    recomendados: ["Michelle Byron de Sweetheath", "Dianna Evans"],
  },
  {
    nombre: "Dianna Evans",
    rol: "Roleadora: Mich",
    biografia: "En desarrollo",
    ocupacion: "Paramedica",
    familia: "En desarrollo",
    amigos: "En desarrollo",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Michelle Byron de Sweetheath", "Harper Byron"],
  },
  {
    nombre: "Lorna Castro",
    rol: "Roleadora: Lolo",
    biografia:
      "Llegó desde Chicago a Los Santos junto a su esposo para dirigir el Hospital General de Los Santos, luego de cinco años es enviada a Asylum por el comité de medicina para dirigir ese hospital. Desde entonces ha habido una mejora tanto de hospital como de los servicios y atención que ofrece en el mismo.",
    ocupacion: "Directora del Hospital General de Asylum/ médico cirujano",
    familia:
      "Albert Castro (padre, inversor capitalista en diversas empresas), Elisabeth Hale (madre, pintora y escritora en sus tiempos libres), Noah Holiday (cónyuge, Jefe de policía)",
    amigos:
      "Wernobyl de Trucazo, Blanca Fermette Gambino, Freddy Trucazo y Hazel Smith",
    historia: [
      "Hija única de Albert Castro y Elisabeth Hale, se interesó en la medicina desde muy joven,  fue una prodigio y se graduó antes de tiempo por lo que aplicó a la universidad desde temprana edad, se especializó en el área de cirugía y ciencias genómicas. Conoció a su actual esposo cuando estaba terminando su residencia, se casaron a los dos años de conocerse.",
      "Sus padres murieron en un accidente aéreo tan solo dos años antes de conseguir el puesto de directora en Los Santos donde residió por cinco años hasta que la trasladaron a Asylum donde conserva el mismo cargo.",
    ],
    curiosidades: [
      "Le gusta pasar tiempo con su esposo en sus ratos libres.",
      "Le gustan los animales aunque no tiene ninguno por la falta de tiempo.",
      "Algún día le gustaría tener hijos propios.",
      "Es una persona bastante profesional.",
      "A pesar de su seriedad es alguien bastante amable y bondadosa.",
    ],
    recomendados: ["Agente X"],
  },
  {
    nombre: "Agente X",
    rol: "Roleadora: Lolo",
    biografia:
      "Esta en la CIA desde que tiene memoria, asesina entrenada, experimento del Proyecto NewGen posteriormente llamado Proyecto X-1278 y gente de nivel 7.",
    ocupacion: "Agente nivel 7, asesina profesional de la CIA",
    familia: "Desconocido",
    amigos: "Cole Hussain",
    historia: [
      "Raptada desde los primeros meses de vida, fue sujeto de experimento en el Proyecto NewGen, proyecto cuyos sujetos de prueba eran los bebés de agentes de nivel 7 para abajo, luego de eso fue entrenada por la división especial de agentes hasta convertirse en una asesina.",
      "Al manifestarse sus poderes, fue recluida en el laboratorio con tan solo diez años para volver a ser sujeto de experimentos; fue liberada de los mismos hasta los veinte y desde entonces fue subiendo de nivel al infiltrarse en misiones y asesinar objetivos de la CIA con ayuda de sus habilidades camaleónicas.",
    ],
    curiosidades: [
      "Debido a su alteración genética, se interesó en las ciencias genómicas y las estudio en su tiempo libre volviéndose una profesional en el tema.",
      "Desarrollo un leve rechazo hacia sus poderes por el trauma que le causaron los experimentos.",
      "De pequeña, cuando sus poderes mentales despertaron, tenía pesadillas.",
      "Cuando recién despertó su poder mental, las voces en su cabeza no tenían forma, solo eran ruidos fuertes y muy molestos.",
      "Sabe diez idiomas entre ellos el ruso, alemán, español, portugués, inglés y un largo etc.",
      "Su primera víctima fue a los siete.",
      "Cuando la telekinesis despertó era muy molesta pues terminaba atrayendo objetos involuntariamente.",
    ],
    recomendados: ["Lorna Castro"],
  },
  {
    nombre: "Bo Xin",
    rol: "Roleadora: Lolo",
    biografia:
      "Llegó a Asylum buscando ampliar su negocio y expandir el poder de los Sweet Dreams.",
    ocupacion:
      "Lider de la Mafia Sweet Dreams; conductor profesional de carreras ilegales",
    familia: "Desconocido",
    amigos: "Luis, Yados, Eduardo (Abuelo) y Adrián",
    historia: [
      "Empezó a delinquir a los trece años, edad en la cuál su padre Buah lo abandonó. Años después conoció a Luis, Yados y al abuelo formando así la banda de los Sweet Dreams; luego de mucho trabajo en el mundo ilegal se lograron posicionar como la mafia de armas y cocaína más poderosa de Los Santos.",
    ],
    curiosidades: [
      "Adora correr en carreras ilegales.",
      "Le encanta comprarse coches y luego tunearlos a su gusto.",
      "Su mejor amigo es Luisito.",
      "Su película favorita es Mulan.",
      "Le encanta la música K-pop.",
    ],
    recomendados: ["Adrián Firestone", "Lorna Castro"],
  },
  {
    nombre: "Blanca Fermette Gambino",
    rol: "Roleadora: Blanca",
    biografia:
      "Nació en Sicilia, Italia. Hija menor de los Gambino. Criada y entrenada para hacerse cargo de la CIA. Estudió psiquiatría y criminología. Llegó a Los Santos y al pueblo de Asylum en busca de algo en qué ocuparse y alejarse de su madre.",
    ocupacion:
      "Jefa de la CIA y del departamento de psiquiatría del hospital de Asylum",
    familia:
      "Tommaso Gambino (padre, ex-capo de la Cosa Nostra e inversionista. Actualmente fallecido.), Felice Castellano (madre, antigua jefa de la CIA), Toni Gambino (hermano mayor, capo de la Cosa Nostra y dueño de la cadena de supermercados Krule), Carlo Gambino (segundo hermano mayor, capo de la Cosa Nostra y dueño de la cadenas de supermercados Krule) y Daniela Gambino Lop (esposa, dueña del casino)",
    amigos:
      "Dani Gambino Lop, Wernobyl de Trucazo, Carlie Lim, Vanu Lop, Toni Gambino, Carlo Gambino, Brillith y Lorna Castro",
    historia: [
      "Desde pequeña fue criada como militar y entrenada de todas las maneras posibles para ser una jefa y saber todo tipo de defensa personal. Fue retenida en las instalaciones de la CIA durante toda su niñez y juventud donde fue torturada por agentes y su propia madre, y la mantuvieron lejos de sus hermanos. Estudió psiquiatría y criminología mientras estaba comprometida.",
      "Llegó a Los Santos para librarse de su madre y rompió su antiguo compromiso, el cual fue un trato a sus espaldas y se enteró el mismo día que su boda. Fue casi obligada a casarse y ese mismo día llegó a Los Santos. Su objetivo principal en la CIA es cambiar el sistema antiguo de su madre y hacer mejor las cosas.",
    ],
    curiosidades: [
      "Suele ser demasiada amable y generosa con las personas.",
      "Es difícil ganar su aprecio.",
      "Cree que todos son sus ratas de laboratorio exceptuando sus amigos y familia.",
      "Es ludópata. Cree que es genético.",
      "Diagnosticada con bipolaridad.",
      "Posee signos de ser sociopata.",
      "Es demasiado observadora y calculadora.",
      "Excesivamente manipuladora e inteligente.",
      "Casi nunca se calla.",
      "La familia es primero.",
      "Es sádica y despiadada cuando es necesario.",
      "No puede tener hijos.",
    ],
    recomendados: ["Toni Gambino", "Carlo Gambino"],
  },
  {
    nombre: "Freddy Trucazo",
    rol: "Roleadora: Blanca",
    biografia:
      "Nació en Galicia, España. Juventud relativamente normal. Se mudó a Los Santos desde joven. Formó parte de una banda y actualmente agente de la CIA.",
    ocupacion:
      "Agente Nivel 7 de la CIA y Superintendente de la LSPD,Los Santos Police Department y Juez.",
    familia:
      "Ricardo Trucazo (padre, carpintero. Actualmente fallecido.), Genoveva Trucazo (madre, sin ocupación registrada. Actualmente fallecida.), José María Trucazo (hermano mayor, jefe de la banda SL. Actualmente fallecido.) y Wernobyl Trucazo (esposa, abogada)",
    amigos: "Wernobyl Trucazo, Lorna Castro y Noah Holiday",
    historia: [
      "Se mudó a Los Santos siendo joven. En su juventud, formó parte del Cuerpo Nacional de Policia, CNP, pero fue despedido por comportamiento inadecuado. Inició una banda criminal junto a su hermano llamada SL. Después fue reclutado por Jack Conway en el CNI que posteriormente cambió su nombre a CIA. Su misión actual es mantener a la ciudad de Los Santos estable como Superintendente de la LSPD.",
    ],
    curiosidades: [
      "Padece de transtorno de identidad disociativo parcial.",
      "Actualmente se sabe que solo tiene un Alter que se hace llamar Toro.",
      "Es extremadamente, inteligente, manipulador y persuasivo.",
      "Se destaca en la agencia por ser sicario.",
      "No le gusta relacionarse con las personas o profundizar relaciones.",
      "Siempre quiso ser padre.",
      "Mató a su hermano.",
    ],
    recomendados: ["Wernobyl Trucazo", "Isidoro Navarro"],
  },
  {
    nombre: "Toni Gambino",
    rol: "Roleadora: Blanca",
    biografia:
      "Nació en Sicilia, Italia. Hermano mayor de la familia Gambino. Fue criado en casa y formado para ser el sucesor del imperio de su padre.",
    ocupacion:
      "Capo de la Cosa Nostra y Jefe/Dueño de la cadena de supermercados Krule",
    familia:
      "Tommaso Gambino (padre, ex-capo de la Cosa Nostra e inversionista. Actualmente fallecido.), Felice Castellano (madre, antigua jefa de la CIA), Carlo Gambino (hermano menor, capo de la Cosa Nostra y dueño de la cadenas de supermercados Krule) y Blanca Fermette Gambino (hermana menor, jefa de la CIA y psiquiatra)",
    amigos:
      "Carlo Gambino, Blanca Fermette Gambino, Gasolino López, José Heredia, Igor y Hai Cheng",
    historia: [
      "Desde pequeño fue criado como el jefe de la familia. Criado en casa y entrenado para formar parte y llevar la mafia de su padre. Fue destinado como el heredero de la Cosa Nostra. Se le enseñó a manejar armas y a ser buen negociador. Llegó a Marbella para establecer las bases del nuevo imperio después de la muerte de su padre y allí tuvo problemas con la policía y el FBI. Huyó junto a otros conocidos y amigos suyos en un avión y pidió asilo a su hermana. Después voló a Los Santos y actualmente se hospeda en Asylum. Sigue con su cadena de supermercados y establece la base para un nuevo imperio bajo la tutela de la CIA.",
    ],
    curiosidades: [
      "Su padre siempre lo tachó de blando.",
      "Es muy inteligente y buen negociador.",
      "Ama a su mafia, pero prefiere el Krule.",
      "Es ludópata. Piensa que es genético.",
      "Siempre viste de traje.",
      "Fiel creyente religioso.",
      "Padece de heterocromía.",
      "Es demasiado amable para su puesto.",
      "Sobreprotector.",
      "Tenía pésima puntería hasta que su hermana le enseñó.",
    ],
    recomendados: ["Blanca Fermette Gambino", "Carlo Gambino"],
  },
  {
    nombre: "Vanu Lop",
    rol: "Roleadora: Internet Explorer",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Blanca Fermette Gambino", "Freddy Trucazo"],
  },
  {
    nombre: "Wernobyl Trucazo",
    rol: "Roleadora: Wen",
    biografia:
      "Llegó desde México a la edad de 12 años después de ser adoptada por Dem y Mad. Desde entonces no ha regresado a México, creció y formó su familia en Asylum.",
    ocupacion: "Abogada",
    familia:
      "Dem Johnson (padre, fallecido. Dios), Mad Johnson (madre, Sacerdotisa principal de la iglesia Asylum), Shey (hermana, sin ocupación), Nikaru Morningstar(madrastra, sin ocupación), Alexander Johnson (abuelo Paterno, Sacerdote líder de la Catedral Metropolitana. Argentina) y Freddy Trucazo (esposo, Superintendente LSP)",
    amigos:
      "Freddy Trucazo, Dani Gambino Lop, Blanca Gambino Lop, Lorna Castro, Puchula",
    historia: [
      "Nació y creció en México hasta la edad de doce años, edad en la cuál sus padres la adoptaron y trasladaron a Asylum, lugar que desde entonces ha sido su residencia. Se graduó de derecho en la universidad convirtiéndose luego en la mejor abogada de Asylum; conoció a su actual esposo en un juicio cuando ejercía su profesión.",
      "Sufrió un trauma cuando vio como su padre se degollaba en un intento de salvación hacia su madre. Fue secuestrada por la CIA al intentar huir junto a su esposo después de enterarse que estaba embarazada. Actualmente se encuentra gestando gemelos. No confía en nadie más que en su esposo y su mejor amiga.",
    ],
    curiosidades: [
      "Tiene una fijación por las cicatrices.",
      "Creció con el rechazo de su padre.",
      "Tomo de ejemplo la relación tóxica de sus padres para la propia.",
      "Tiene depresión, ansiedad, baja autoestima y apego ansioso.",
      "Tiene una relación obsesiva y posesiva con su esposo.",
      "Guarda partes del cuerpo de sus victimas como “Trofeos de Relación”.",
      "Es bastante protectora con sus seres queridos.",
      "Comparte una cicatriz ubicada en la mano izquierda con su esposo.",
      "Tiene en su pecho marcado el nombre de “Toro”.",
      "Tiene un perrhijo llamado “Canwey”",
      "Le encantan las coronas y las rosas.",
    ],
    recomendados: ["Freddy Trucazo", "Adrián Firestone"],
  },
  {
    nombre: "Brillith Torres",
    rol: "Roleadora: Brillos",
    biografia: "Llegó a Asylum por la misión que le encargó el FBI.",
    ocupacion: "Ex agente del FBI/ Dueña de la Cafetería de Asylum",
    familia: "Desconocido",
    amigos: "Pame Liu",
    historia: [
      "Fue entrenada en el FBI convirtiéndose en agente, llegó a Asylum cuando su jefa Vanu le encargó la misión de enamorar a Mad para sacar información de la misma. Luego de que todo saliera mal le borraron la memoria con ayuda de la CIA; tuvo que cambiar su aspecto físico y actualmente tiene una cafetería además de estar comprometida con la comisaría de Asylum.",
    ],
    curiosidades: [
      "Aprendió todo lo que sabe de cocina por su abuela.",
      "Se encariña rápido.",
      "Siempre quiso tener su propia familia.",
      "Le gusta mucho dar regalos a los que aprecia.",
      "Tener su propia cafetería es lo que siempre quiso.",
    ],
    recomendados: ["Blanca Fermette Gambino", "Adrián Firestone"],
  },
  {
    nombre: "Mei Feng",
    rol: "Roleadora: Mara",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Sarah Firestone", "Adrián Firestone"],
  },
  {
    nombre: "Jasha Volkov",
    rol: "Roleadora: Carlie",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Maxim Zaitsev"],
  },
  {
    nombre: "Carlo Gambino",
    rol: "Roleadora: Carlie",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Toni Gambino", "Blanca Fermette Gambino"],
  },
  {
    nombre: "Carlie Lim",
    rol: "Roleadora: Carlie",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Carlo Gambino"],
  },
  {
    nombre: "Maxim Zaitsev",
    rol: "Roleadora: Carlie",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Jasha Volkov"],
  },
  {
    nombre: "Bianca Madison Johnson",
    rol: "Roleadora: Madness",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Wernobyl Trucazo", "Nikaru Morningstar"],
  },
  {
    nombre: "Nikaru Morningstar",
    rol: "Roleadora: Nika",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Bianca Madison Johnson", "Wernobyl Trucazo"],
  },
  {
    nombre: "Alissa White-gluz",
    rol: "Roleadora: Nika",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Charlotte White-gluz"],
  },
  {
    nombre: "Charlotte White-gluz",
    rol: "Roleadora: Madness",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Alissa White-gluz", "Freddy Trucazo"],
  },
  {
    nombre: "Jennifer King",
    rol: "Roleadora: Wen",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Elijah Müller", "Myke King"],
  },
  {
    nombre: "Laoviah",
    rol: "Roleadora: Madness",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Bianca Madison Johnson", "Milagros Johnson"],
  },
  {
    nombre: "Milagros Johnson",
    rol: "Roleadora: Madness",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Bianca Madison Johnson", "Laoviah"],
  },
  {
    nombre: "Elijah Müller",
    rol: "Roleadora: Wen",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Myke King", "Jennifer King"],
  },
  {
    nombre: "Myke King",
    rol: "Roleadora: Wen",
    biografia: "En desarrollo",
    ocupacion: "Desconocido",
    familia: "Desconocido",
    amigos: "Desconocido",
    historia: ["En desarrollo"],
    curiosidades: ["En desarrollo"],
    recomendados: ["Elijah Müller", "Jennifer King"],
  },
];
